### ISSUE TITLE
Any plans to support TSNE with PCA init?

### ISSUE THREAD

**Issue by mitming** [CannyLab/tsne-cuda#104]
Hi @DavidMChan, 

Are there any plans to support TSNE with PCA initiation?

**Comment by mitming** [comment]
> There are no plans to support this natively right now. Instead, it's best to use any PCA library to compute the PCA transform of the vectors, then pass the resulting transformed vectors to TSNE-CUDA.

Got it , thanks a lot!

**Comment by mitming** [comment]
Hi @DavidMChan , could you please provide some advice about the PCA library with GPU accelerate?

**Comment by DavidMChan** [comment]
This is provided by many libraries -
pytorch: https://pytorch.org/docs/stable/generated/torch.pca_lowrank.html
tensorflow: https://www.tensorflow.org/tfx/transform/api_docs/python/tft/pca
skcuda: https://scikit-cuda.readthedocs.io/en/latest/generated/skcuda.linalg.PCA.html

It is also a relatively fast CPU operation with support for multithreading in scikit learn.

**Comment by mitming** [comment]
> This is provided by many libraries -
> pytorch: https://pytorch.org/docs/stable/generated/torch.pca_lowrank.html
> tensorflow: https://www.tensorflow.org/tfx/transform/api_docs/python/tft/pca
> skcuda: https://scikit-cuda.readthedocs.io/en/latest/generated/skcuda.linalg.PCA.html
> 
> It is also a relatively fast CPU operation with support for multithreading in scikit learn.

Thanks again!
