### ISSUE TITLE
MultiGPU support

### ISSUE THREAD

**Issue by ferrine** [CannyLab/tsne-cuda#106]
Hey, I'm using this great repo on really massive data with great success. Many thanks for your work. 

Do you have plans for multigpu support so it can handle more data or work even faster?

**Comment by DavidMChan** [comment]
This library already supports multi-gpu in sharded search when computing the nearest neighbors (I think by default it will use all available GPUs), however multi-gpu t-SNE is non-trivial, and not something that's currently on our roadmap. We'd love contributions, however!
