### ISSUE TITLE
Memory leak using fit_transform

### ISSUE THREAD

**Issue by DradeAW** [CannyLab/tsne-cuda#108]
Hi,

I've been trying to use `tsnecuda` on my dataset, but I keep getting memory errors even though I'm using relatively small dataset.

My array is a `100000x375` of `int16` (= 72MB), and I'm running the software on a RTX 2080 8GB.
When running `TSNE(n_components=2).fit_transform(data)`, the GPU memory usage jumps from 0% to 100% in less than 2 seconds and I get the following error:

```
terminate called after throwing an instance of 'faiss::FaissException'
  what():  Error in virtual void* faiss::gpu::StandardGpuResourcesImpl::allocMemory(const faiss::gpu::AllocRequest&) at /faiss/faiss/gpu/StandardGpuResources.cpp:410: Error: 'err == cudaSuccess' failed: Failed to cudaMalloc 1500000000 bytes on device 1 (error 2 out of memory
Outstanding allocations:
Alloc type FlatData: 2 allocations, 475264 bytes
Alloc type TemporaryMemoryBuffer: 1 allocations, 536870912 bytes
Alloc type Other: 5 allocations, 102200000 bytes
Alloc type IVFLists: 632 allocations, 217884672 bytes

Aborted
```

This looks like a memory leak?
I've installed faiss and tsnecuda in conda using `conda install -c CannyLab -c pytorch tsnecuda`, and the test ran without a problem.
This problem happens in cuda 10.1 and cuda 10.2.
I've tried tsnecuda a few months ago (somewhere in may I believe), and it worked fine then.

**Comment by DavidMChan** [comment]
Can you try running the code with CUDA_VISIBLE_DEVICES=X (where X is the device identifier from `nvidia-smi` corresponding to the 2080)? Because we use a mirrored split, if you're not careful it will try to put the full NN map on both GPUs (regardless of memory availability)
