### ISSUE TITLE
Critical Execution Error

### ISSUE THREAD

**Issue by ktamiola** [CannyLab/tsne-cuda#11]
**Steps to reproduce**
Compile `tsnecuda` from source and launch `tsne`.

**Configuration**
```
NVIDIA Tools:
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Sep__1_21:08:03_CDT_2017
Cuda compilation tools, release 9.0, V9.0.176

GPU:
Tesla V100-SXM2-16gb
NVIDIA Driver Version: 396.37
```

**Error**
```
Starting TSNE calculation with 5000 points.
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  parallel_for failed: invalid device function
Aborted (core dumped)
```

**Comment by DavidMChan** [comment]
This is a new one, and likely due to the Volta GPU (which none of us have, so it might be a bit tricky to debug). If you haven't already, can you add the line 
```
-gencode=arch=compute_70,code=sm_70
```
to replace the similar 5.2 and 6.0 lines 62 of the CMakeLists.txt file? Because the volta GPU bumps the compute capability - and we don't actually handle that cleanly in the CMakeLists. If you've already done this - is it possible to get the results of a GDB stack trace on the call, so I can figure out which kernel is failing?

In addition, since you're using a Volta card, you may want to edit the GPU options in /src/include/options.h, since without changing them, you may have reduced performance. Unfortunately, we can't do this optimization due to the lack of hardware.

**Comment by ktamiola** [comment]
Understood. Let me do the edits and come back to you.

**Comment by chunjiangzhu** [comment]
Dear @DavidMChan ,
We encountered the same error, but we installed tsnecuda by pip install.

Results of deviceQuery:

> ./deviceQuery Starting...
> 
>  CUDA Device Query (Runtime API) version (CUDART static linking)
> 
> Detected 2 CUDA Capable device(s)
> 
> Device 0: "Tesla K40c"
>   CUDA Driver Version / Runtime Version          9.0 / 9.0
>   CUDA Capability Major/Minor version number:    3.5
>   Total amount of global memory:                 11440 MBytes (11995578368 bytes)
>   (15) Multiprocessors, (192) CUDA Cores/MP:     2880 CUDA Cores
>   GPU Max Clock rate:                            745 MHz (0.75 GHz)
>   Memory Clock rate:                             3004 Mhz
>   Memory Bus Width:                              384-bit
>   L2 Cache Size:                                 1572864 bytes
>   Maximum Texture Dimension Size (x,y,z)         1D=(65536), 2D=(65536, 65536), 3D=(4096, 4096, 4096)
>   Maximum Layered 1D Texture Size, (num) layers  1D=(16384), 2048 layers
>   Maximum Layered 2D Texture Size, (num) layers  2D=(16384, 16384), 2048 layers
>   Total amount of constant memory:               65536 bytes
>   Total amount of shared memory per block:       49152 bytes
>   Total number of registers available per block: 65536
>   Warp size:                                     32
>   Maximum number of threads per multiprocessor:  2048
>   Maximum number of threads per block:           1024
>   Max dimension size of a thread block (x,y,z): (1024, 1024, 64)
>   Max dimension size of a grid size    (x,y,z): (2147483647, 65535, 65535)
>   Maximum memory pitch:                          2147483647 bytes
>   Texture alignment:                             512 bytes
>   Concurrent copy and kernel execution:          Yes with 2 copy engine(s)
>   Run time limit on kernels:                     No
>   Integrated GPU sharing Host Memory:            No
>   Support host page-locked memory mapping:       Yes
>   Alignment requirement for Surfaces:            Yes
>   Device has ECC support:                        Enabled
>   Device supports Unified Addressing (UVA):      Yes
>   Supports Cooperative Kernel Launch:            No
>   Supports MultiDevice Co-op Kernel Launch:      No
>   Device PCI Domain ID / Bus ID / location ID:   0 / 2 / 0
>   Compute Mode:
>      < Default (multiple host threads can use ::cudaSetDevice() with device simultaneously) >
> 
> Device 1: "Tesla K40c"
>   CUDA Driver Version / Runtime Version          9.0 / 9.0
>   CUDA Capability Major/Minor version number:    3.5
>   Total amount of global memory:                 11440 MBytes (11995578368 bytes)
>   (15) Multiprocessors, (192) CUDA Cores/MP:     2880 CUDA Cores
>   GPU Max Clock rate:                            745 MHz (0.75 GHz)
>   Memory Clock rate:                             3004 Mhz
>   Memory Bus Width:                              384-bit
>   L2 Cache Size:                                 1572864 bytes
>   Maximum Texture Dimension Size (x,y,z)         1D=(65536), 2D=(65536, 65536), 3D=(4096, 4096, 4096)
>   Maximum Layered 1D Texture Size, (num) layers  1D=(16384), 2048 layers
>   Maximum Layered 2D Texture Size, (num) layers  2D=(16384, 16384), 2048 layers
>   Total amount of constant memory:               65536 bytes
>   Total amount of shared memory per block:       49152 bytes
>   Total number of registers available per block: 65536
>   Warp size:                                     32
>   Maximum number of threads per multiprocessor:  2048
>   Maximum number of threads per block:           1024
>   Max dimension size of a thread block (x,y,z): (1024, 1024, 64)
>   Max dimension size of a grid size    (x,y,z): (2147483647, 65535, 65535)
>   Maximum memory pitch:                          2147483647 bytes
>   Texture alignment:                             512 bytes
>   Concurrent copy and kernel execution:          Yes with 2 copy engine(s)
>   Run time limit on kernels:                     No
>   Integrated GPU sharing Host Memory:            No
>   Support host page-locked memory mapping:       Yes
>   Alignment requirement for Surfaces:            Yes
>   Device has ECC support:                        Enabled
>   Device supports Unified Addressing (UVA):      Yes
>   Supports Cooperative Kernel Launch:            No
>   Supports MultiDevice Co-op Kernel Launch:      No
>   Device PCI Domain ID / Bus ID / location ID:   0 / 4 / 0
>   Compute Mode:
>      < Default (multiple host threads can use ::cudaSetDevice() with device simultaneously) >
> > Peer access from Tesla K40c (GPU0) -> Tesla K40c (GPU1) : Yes
> > Peer access from Tesla K40c (GPU1) -> Tesla K40c (GPU0) : Yes
> 
> deviceQuery, CUDA Driver = CUDART, CUDA Driver Version = 9.0, CUDA Runtime Version = 9.0, NumDevs = 2
> Result = PASS





Code:

> import numpy as np
> from tsnecuda import TSNE
> X = np.array([[0, 0, 0], [0, 1, 1], [1, 0, 1], [1, 1, 1]])
> X_embedded = TSNE().fit_transform(X)
> print(X_embedded.shape)



Error:

> terminate called after throwing an instance of 'thrust::system::system_error'
>   what():  parallel_for failed: invalid device function
> Aborted (core dumped)

Any suggestions for us? Thanks a lot!

**Comment by DavidMChan** [comment]
You have issue #18. In general, please refrain from commenting on closed issues - in the future please open a new issue and reference the old issue in your post.
