### ISSUE TITLE
403 Error when downloading wheels

### ISSUE THREAD

**Issue by TonyLianLong** [CannyLab/tsne-cuda#111]
When downloading https://s3.us-west-1.wasabisys.com/tsnecuda/tsnecuda-3.0.1+cu101-py3-none-any.whl I get:
<img width="808" alt="image" src="https://user-images.githubusercontent.com/1451234/176948546-04895e6c-1bd0-4e87-9e4b-88432e5b3d48.png">

**Comment by DavidMChan** [comment]
This should be resolved now! Sorry for the inconvenience.
