### ISSUE TITLE
stuck at Initializing cuda handles

### ISSUE THREAD

**Issue by SwingWillwow** [CannyLab/tsne-cuda#122]
I successfully install the tsne-cuda using conda but my program stuck at initializing cuda handles. Any possible reasons?

**Comment by DavidMChan** [comment]
Can I get some more information?

- What is your OS version?
- What is your CUDA version?
- What GPU do you have?
- What is your NVIDIA driver version?
- Are there any errors besides the code getting stuck?

**Comment by kvey** [comment]
similar experience but I believe the issue was I had CUDA 12 on the host and the package support ends at 11.3

**Comment by DavidMChan** [comment]
3.0.2 (and the distributed backports to 3.0.1) adds CUDA 12 support (We'll have to figure out how to upstream this).
