### ISSUE TITLE
Gradient problem

### ISSUE THREAD

**Issue by fengyuxie** [CannyLab/tsne-cuda#125]
This project has been implemented very well. It would be great if we could replace the numpy in it to support gradients. The current version of the code cannot be directly used in neural networks (as there will be errors if there are no gradients).

**Comment by DavidMChan** [comment]
We're happy that you appreciate the project, however it's unlikely that this code will ever support gradients, as tsne is a non-parametric algorithm, and the computation required to support gradients would not only be a significant mathematical undertaking, but add significant overhead to the forward pass.
