### ISSUE TITLE
ImportError: libcudart.so.11.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by rsrcoderplay** [CannyLab/tsne-cuda#126]
ImportError: libcudart.so.11.0: cannot open shared object file: No such file or directory

**Comment by DavidMChan** [comment]
This is likely due to an incorrect linked CUDA library (or the lack of CUDA on your system). Make sure that you have CUDA installed, and that libcudart.so.11.0 is on your link path (or use LD_LIBRARY_PATH to correct this).
