### ISSUE TITLE
Binary installation for Windows10 not possible

### ISSUE THREAD

**Issue by raulmendez** [CannyLab/tsne-cuda#131]
Conda installation conda install tsnecuda -c conda-forge DOES NOT find any files, whereas pip3 binary installation pip3 install tsnecuda==3.0.1+cu113 -f https://tsnecuda.isx.ai/tsnecuda_stable.html (downloading the corresponding linked wheel file locally), it does the installation but using Linux libraries, (but then it comes, for instance with **libtsnecuda.so** instead of libtsnecuda.dll). Any recommendations about how to install it on Windows 10?

**Comment by DavidMChan** [comment]
We don't officially support windows, however there's a PR #130 which allows you to build from source! We're looking to get it merged with the conda recipe eventually.

**Comment by raulmendez** [comment]
Hi David,
The link you mentioned PR https://github.com/CannyLab/tsne-cuda/pull/130 does not provide the txt nor explicit instructions. I would need some more details to be able to installed it on my Windows (I tried the TSNE funciton at sklearn,.. but it is so slow).

Thanks!
