### ISSUE TITLE
Fit and Transform

### ISSUE THREAD

**Issue by ElijahBiocinth** [CannyLab/tsne-cuda#135]
Greetings
Have you considered implementing fit and transform separately on cuda? Like here
https://github.com/scikit-learn/scikit-learn/issues/5361

**Comment by DavidMChan** [comment]
Since T-SNE is a non-parametric algorithm, it doesn't make much sense to do continual embeddings. There are parametric versions: https://github.com/kylemcdonald/Parametric-t-SNE, however we have no plans to implement them at this time.
