### ISSUE TITLE
Unnecessary FAISS Memory Consumption on Multi-GPU Machines

### ISSUE THREAD

**Issue by ehsansaleh** [CannyLab/tsne-cuda#137]
Hi there and thank you so very much for the great library!

When I'm running 4 independent programs on a 4-GPU machine, Once I spin up tsne-cuda, I see that 16 processes get spawned occupying ~250MBs CUDA Memory per process. This is somewhat wasteful. I believe a single GPU should be enough for tsne-cuda in my application.

I believe the following line is responsible for this behavior.

https://github.com/CannyLab/tsne-cuda/blob/44249b6895a2eb389b8a13390ed6fb125d2040c8/src/util/distance_utils.cu#L99

Could you please consider giving the user more control over the GPU devices used by tsne-cuda?

Sincerely, Ehsan

**Comment by DavidMChan** [comment]
The best thing to do here is just to use CUDA_VISIBLE_DEVICES to control the usage of the individual GPUs (since tsnecuda will always try to use all available gpus).

**Comment by ehsansaleh** [comment]
I see. This workaround can certainly solve the issue for me.

Appreciate the nanosecond response. Cheers!
