### ISSUE TITLE
Asking support for Mac OS

### ISSUE THREAD

**Issue by TomHeaven** [CannyLab/tsne-cuda#15]
Hi, I try to compile your code on Mac OS, but without success. There is a problem that default XCode clang compiler does not support OpenMP. 

It seems third_party dependencies rely on OpenMP and report the following error:
```shell
/Users/tomheaven/Documents/libraries/tsne-cuda/third_party/faiss/IndexHNSW.h:12:10: fatal error: 'omp.h' file not found
#include <omp.h>
```
As we only want the CUDA acceleration, can there be an option to disable that feature so the code will compile smoothly?

Thanks!

**Comment by ktamiola** [comment]
Please follow: 
https://github.com/facebookresearch/faiss/blob/master/INSTALL.md

To be more specific:
```
Notes for build on Mac: The native compiler on Mac does not support OpenMP. So to make it work on Mac, you have to install a new compiler using either Macports or Homebrew. For example, after installing the compiler g++-mp-6 from Macports (port install g++-mp-6), you need to set the two flags CMAKE_CXX_COMPILER and CMAKE_C_COMPILER:

cmake -DCMAKE_CXX_COMPILER=/opt/local/bin/g++-mp-6 -DCMAKE_C_COMPILER=/opt/local/bin/gcc-mp-6 ..

Similarly, you can use Homebrew to install clang++ (brew install llvm) and then set the two flags to /usr/local/opt/llvm/bin/clang++
```

**Comment by DavidMChan** [comment]
@TomHeaven  - Can you report if this worked? We've never tried OSX compilation (since most apple systems either don't have a GPU or have AMD GPUs) - and it would be interesting to see if this is even possible.

**Comment by TomHeaven** [comment]
@DavidMChan The problem can be solved by installing OpenMP
```
brew install libomp
brew link --overwrite libomp
```
