### ISSUE TITLE
parallel_for failed: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by Seanny123** [CannyLab/tsne-cuda#18]
**Error**
```
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  parallel_for failed: no kernel image is available for execution on the device
Aborted (core dumped)
```

**Code to reproduce**
```
from tsnecuda import TSNE
import numpy as np

N = int(1e5)
n_iter = 1000

X = np.random.rand(N, 2)
X_embedded = TSNE(n_components=2, verbose=1, n_iter=n_iter, num_neighbors=32).fit_transform(X)

print("Done")
```

**Configuration**
```
Tesla K80
Driver Version: 396.44
```

**Compiled from source using**
```
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Sep__1_21:08:03_CDT_2017
Cuda compilation tools, release 9.0, V9.0.176
```

Looking at the `conda_support` branch, does this have something to do with `gencode` and `code` flags in `CMakeLists.txt`?

**Comment by Seanny123** [comment]
Yep, when I used `-gencode=arch=compute_37,code=sm_37` everything worked fine.

**Comment by cibinjohn** [comment]
> Yep, when I used `-gencode=arch=compute_37,code=sm_37` everything worked fine.

Hi,
I am facing similar issue while running a python code, which uses cuda.
Could you share the details about how you specified -gencode=arch=compute_37,code=sm_3

Thanks

**Comment by DavidMChan** [comment]
The architecture/compute codes which are specified depend on your GPU - see: https://arnon.dk/matching-sm-architectures-arch-and-gencode-for-various-nvidia-cards/ for a table on matching the specific codes.

**Comment by JXuann** [comment]
@DavidMChan  where/how could I specify `-gencode=arch=compute_xx,code=sm_xx`? It's my first time encountering it and I have not found any answers online after searching around. Many thanks in advance!
