### ISSUE TITLE
terminate called after throwing an instance of 'thrust::system::system_error'

### ISSUE THREAD

**Issue by cmartinezfleites** [CannyLab/tsne-cuda#20]
Hi, 

thank you again for the conda option. 

I installed:
"conda install tsnecuda cuda91 -c cannylab -c numba"

in a linux RHEL v7 with Cuda compilation tools, release 9.1, V9.1.85
the GPU hardware is  8 x Tesla P100

if more info is needed please let me know.

I am getting the following error:

Python 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56)
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> from tsnecuda import TSNE
>>> X = np.array([[0, 0, 0], [0, 1, 1], [1, 0, 1], [1, 1, 1]])
>>> X_embedded = TSNE(perplexity=64.0, learning_rate=270).fit_transform(X)
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  parallel_for failed: invalid device function
Aborted (core dumped)

**Comment by tabaspki** [comment]
Hi,
I'm also having the same exact issue. 
Im using an Ubuntu 16.04 with CUDA toolkit 8.0 and Tesla V100 cards. I've tried with conda (with cuda80 version, and also building from sources...

The error is exactly the same:
`terminate called after throwing an instance of 'thrust::system::system_error'`
 ` what():  function_attributes(): after cudaFuncGetAttributes: invalid device function`
`Aborted (core dumped)`

**Comment by rmrao** [comment]
I'm not sure what this error is. There's a new fit_tsne branch that implements a FFT version of tSNE instead of the current barnes-hut version. This seems to be more stable (it's also faster). If you're still interested, you could try compiling that branch and seeing if it works. We'll be putting that version on conda eventually also.

**Comment by norveclibalikci** [comment]
I have the same issue, here are my configurations:

Driver: 384
Cuda Version: 9
GPU: Nvidia P100
Python version: 3.6

**Comment by DavidMChan** [comment]
@norveclibalikci - Are you compiling with the correct architecture flags for your GPU on the fit_tsne branch? Usually these errors occur when the device functions don't match up with the compiled functions in the code.

**Comment by norveclibalikci** [comment]
@DavidMChan hey, thanks for the fast reply! I installed via conda, now I am compiling from source.

**Comment by norveclibalikci** [comment]
@DavidMChan yay, it worked!

**Comment by p3732** [comment]
Would be nice to have this version on Conda, seeing that the current version apparently does not work for most folks :)

**Comment by rmrao** [comment]
@p3732 working on it - conda builds with CUDA (and especially with multiple CUDA versions) are very frustrating and none of us have significant experience in this area. The fixes have been migrated to master in #39 and we're trying to get the conda build working as well.

**Comment by rmrao** [comment]
Frankly only the PyTorch people seem to have this figured out...

**Comment by rmrao** [comment]
New release has been pushed to conda for CUDA versions 9.0, 9.1, 9.2, 10.0, and 10.1. You can install with `conda install tsnecuda cuda<major><minor> -c cannylab`.

Closing because I think the original issue and the conda updates have both been solved.
