### ISSUE TITLE
unstable execution process

### ISSUE THREAD

**Issue by LeZhengThu** [CannyLab/tsne-cuda#22]
Hi, I used your lastest conda method to install tsne-cuda "conda install tsnecuda -c cannylab" and my cuda version is 9.0. The installation went well, but I tested the code something wired happened.
I randomly created a data matrix 40000*100, and used a for loop to compute multiple projections with the same data matrix. As you can see, the first three iterations worked fine, but the fourth never returned a result. 

![image](https://user-images.githubusercontent.com/18341929/46564787-78c02580-c8be-11e8-985a-1d7d1dc9e602.png)

**Comment by rmrao** [comment]
This should probably be fixed by #39, which makes a lot of stability improvements. This update hasn't been pushed to conda yet, but if you compile from source it should work for you.

**Comment by rmrao** [comment]
Pushed CUDA 9.0 binaries to conda. You can install with `conda install tsnecuda cuda90 -c cannylab`. Note that I got rid of the 'default' download so you will have to specify the cuda version (this does not download cuda it just tells anaconda which version to select).
