### ISSUE TITLE
details: CUDA error 8

### ISSUE THREAD

**Issue by arashno** [CannyLab/tsne-cuda#23]
Hi,
I keep getting the following error.
I am using CUDA 9.1 and I installed the tsnecuda using conda.

Faiss assertion 'err__ == cudaSuccess' failed in void faiss::gpu::runL2Norm(faiss::gpu::Tensor<T, 2, true, TIndex>&, faiss::gpu::Tensor<T, 1, true, TIndex>&, bool, cudaStream_t) [with T = float; TVec = float4; TIndex = int; cudaStream_t = CUstream_st*] at /home/rmrao/miniconda3/conda-bld/tsnecuda_1538699373852/work/third_party/faiss/gpu/impl/L2Norm.cu:239; details: CUDA error 8

**Comment by mcgrady-forever** [comment]
i met the same problem like @arashno

**Comment by rmrao** [comment]
It looks like there may be a problem with the CUDA9.1 version of the conda bindings. On top of that it seems to be propagating my path ("/home/rmrao...") so clearly I did something wrong when building the binary. Have you tried compiling from source by any chance? I will try to fix the conda bindings in the coming weeks.

**Comment by DavidMChan** [comment]
This should be resolved with the latest binaries. Feel free to reopen if necessary.
