### ISSUE TITLE
OSError: no file with expected extension

### ISSUE THREAD

**Issue by fabien-w** [CannyLab/tsne-cuda#26]
Hi,
In windows, I get the following error during run time:

Python 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 10:22:32) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from tsnecuda import TSNE
>>> import numpy as np
>>> X = np.random.random((5000, 50))
>>> TSNE(verbose=1).fit_transform(X)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\tsnecuda\TSNE.py", line 110, in __init__
    self._lib = N.ctypeslib.load_library('libtsnecuda', self._path) # Load the ctypes library
  File "C:\Users\fabie\AppData\Roaming\Python\Python36\site-packages\numpy\ctypeslib.py", line 155, in load_library
    raise OSError("no file with expected extension")
OSError: no file with expected extension

the error appear at the line of 110 of TNSE.py
with "_path" as the path where is libtsnecuda.so :
>>> N.ctypeslib.load_library('libtsnecuda', _path)
OSError: no file with expected extension

Any idea of what is happening ?

Thanks

**Comment by fabien-w** [comment]
to my understanding, tsnecuda only works in linux, the issue comes frome here

**Comment by DavidMChan** [comment]
Yes, this is the case. Because of upstream dependencies we only support Linux. There's nothing in the source that is Linux dependent, but as far as I know FAISS has Linux only dependencies which makes it tricky to port

**Comment by Po-Shin** [comment]
Hi, I used pip install MulticoreTSNE and got the same error while running my code. Anyone got the solution to fix it?

thanks!

**Comment by Ryan-P-P** [comment]
I'm in trouble with same error. 
but I'm using linux and Cuda version is V10.0 as well. 

what's is the main problem??

**Comment by rmrao** [comment]
@Ryan-P-P please open a new issue with your linux version, GPU version, your method of installation, and the output of `tsnecuda.test()`.
