### ISSUE TITLE
libfaiss.so error

### ISSUE THREAD

**Issue by abhipn** [CannyLab/tsne-cuda#31]
When I try to execute I get an OS Error `libfaiss.so`. I'm using Python 3.6.7 on Ubuntu 18.10 (cuda 9.0)
I then tried to get the conda faiss `linux-64/faiss-gpu-1.5.0-py36_cuda9.0_1.tar.bz2` from [here](https://anaconda.org/pytorch/faiss-gpu/files) but I couldn't find the `libfaiss.so` in it.

```
tsne = TSNE(n_components=2, perplexity=1000,
                n_iter=1500)
```
```
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-5-bf7b6c5abfca> in <module>
     13     tsne = TSNE(n_components=2, perplexity=i,
     14                 learning_rate=200,
---> 15                 n_iter=j)
     16     tsne_data = tsne.fit_transform(x_scaled[:20000, :])
     17     tsne_df[f'Type: {i}_{j}'] = pd.DataFrame(np.vstack([tsne_data.T, y]).T, 

~/.local/lib/python3.6/site-packages/tsnecuda/TSNE.py in __init__(self, n_components, perplexity, early_exaggeration, learning_rate, num_neighbors, force_magnify_iters, pre_momentum, post_momentum, theta, epssq, n_iter, n_iter_without_progress, min_grad_norm, perplexity_epsilon, metric, init, return_style, num_snapshots, verbose, random_seed, use_interactive, viz_timeout, viz_server, dump_points, dump_file, dump_interval, print_interval, device)
    108         # self._faiss_lib = N.ctypeslib.load_library('libfaiss', self._path) # Load the ctypes library
    109         # self._gpufaiss_lib = N.ctypeslib.load_library('libgpufaiss', self._path) # Load the ctypes library
--> 110         self._lib = N.ctypeslib.load_library('libtsnecuda', self._path) # Load the ctypes library
    111 
    112         # Hook the BH T-SNE function

~/.local/lib/python3.6/site-packages/numpy/ctypeslib.py in load_library(libname, loader_path)
    150             if os.path.exists(libpath):
    151                 try:
--> 152                     return ctypes.cdll[libpath]
    153                 except OSError:
    154                     ## defective lib file

/usr/lib/python3.6/ctypes/__init__.py in __getitem__(self, name)
    421 
    422     def __getitem__(self, name):
--> 423         return getattr(self, name)
    424 
    425     def LoadLibrary(self, name):

/usr/lib/python3.6/ctypes/__init__.py in __getattr__(self, name)
    416         if name[0] == '_':
    417             raise AttributeError(name)
--> 418         dll = self._dlltype(name)
    419         setattr(self, name, dll)
    420         return dll

/usr/lib/python3.6/ctypes/__init__.py in __init__(self, name, mode, handle, use_errno, use_last_error)
    346 
    347         if handle is None:
--> 348             self._handle = _dlopen(self._name, mode)
    349         else:
    350             self._handle = handle

OSError: libfaiss.so: cannot open shared object file: No such file or directory

```

**Comment by DavidMChan** [comment]
We have had ongoing issues trying to get this code working with conda. One way to fix this is to point to the libfaiss.so using the LD_LIBRARY_PATH. You should also be able to build the project from source (I would use the fit_tsne branch), which could decrease the painful overhead of making it work. We're working on getting these conda issues resolved, but it's slow going.

**Comment by abhii-p** [comment]
Thank you for responding. I have set the path using `export LD_LIBRARY_PATH=""/usr/local/lib` then I am getting another error when executing `tsnecuda`. 


```
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-2-e5f7bd09822d> in <module>
     13     tsne = TSNE(n_components=2, perplexity=i,
     14                 learning_rate=200,
---> 15                 n_iter=j)
     16     tsne_data = tsne.fit_transform(x_scaled[:20000, :])
     17     tsne_df[f'Type: {i}_{j}'] = pd.DataFrame(np.vstack([tsne_data.T, y]).T, 

~/.local/lib/python3.6/site-packages/tsnecuda/TSNE.py in __init__(self, n_components, perplexity, early_exaggeration, learning_rate, num_neighbors, force_magnify_iters, pre_momentum, post_momentum, theta, epssq, n_iter, n_iter_without_progress, min_grad_norm, perplexity_epsilon, metric, init, return_style, num_snapshots, verbose, random_seed, use_interactive, viz_timeout, viz_server, dump_points, dump_file, dump_interval, print_interval, device)
    108         # self._faiss_lib = N.ctypeslib.load_library('libfaiss', self._path) # Load the ctypes library
    109         # self._gpufaiss_lib = N.ctypeslib.load_library('libgpufaiss', self._path) # Load the ctypes library
--> 110         self._lib = N.ctypeslib.load_library('libtsnecuda', self._path) # Load the ctypes library
    111 
    112         # Hook the BH T-SNE function

~/.local/lib/python3.6/site-packages/numpy/ctypeslib.py in load_library(libname, loader_path)
    150             if os.path.exists(libpath):
    151                 try:
--> 152                     return ctypes.cdll[libpath]
    153                 except OSError:
    154                     ## defective lib file

/usr/lib/python3.6/ctypes/__init__.py in __getitem__(self, name)
    421 
    422     def __getitem__(self, name):
--> 423         return getattr(self, name)
    424 
    425     def LoadLibrary(self, name):

/usr/lib/python3.6/ctypes/__init__.py in __getattr__(self, name)
    416         if name[0] == '_':
    417             raise AttributeError(name)
--> 418         dll = self._dlltype(name)
    419         setattr(self, name, dll)
    420         return dll

/usr/lib/python3.6/ctypes/__init__.py in __init__(self, name, mode, handle, use_errno, use_last_error)
    346 
    347         if handle is None:
--> 348             self._handle = _dlopen(self._name, mode)
    349         else:
    350             self._handle = handle

OSError: /home/abhi/.local/lib/python3.6/site-packages/tsnecuda/libtsnecuda.so: undefined symbol: _ZN5faiss14FaissExceptionC1ERKSsPKcS4_i
```

**Comment by abhii-p** [comment]
> We have had ongoing issues trying to get this code working with conda. One way to fix this is to point to the libfaiss.so using the LD_LIBRARY_PATH. You should also be able to build the project from source (I would use the fit_tsne branch), which could decrease the painful overhead of making it work. We're working on getting these conda issues resolved, but it's slow going.

Thank you for responding. I have set the path using `export LD_LIBRARY_PATH="/usr/local/lib"` then I am getting another error `undefined symbol` when executing `tsnecuda`. 


```
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-2-e5f7bd09822d> in <module>
     13     tsne = TSNE(n_components=2, perplexity=i,
     14                 learning_rate=200,
---> 15                 n_iter=j)
     16     tsne_data = tsne.fit_transform(x_scaled[:20000, :])
     17     tsne_df[f'Type: {i}_{j}'] = pd.DataFrame(np.vstack([tsne_data.T, y]).T, 

~/.local/lib/python3.6/site-packages/tsnecuda/TSNE.py in __init__(self, n_components, perplexity, early_exaggeration, learning_rate, num_neighbors, force_magnify_iters, pre_momentum, post_momentum, theta, epssq, n_iter, n_iter_without_progress, min_grad_norm, perplexity_epsilon, metric, init, return_style, num_snapshots, verbose, random_seed, use_interactive, viz_timeout, viz_server, dump_points, dump_file, dump_interval, print_interval, device)
    108         # self._faiss_lib = N.ctypeslib.load_library('libfaiss', self._path) # Load the ctypes library
    109         # self._gpufaiss_lib = N.ctypeslib.load_library('libgpufaiss', self._path) # Load the ctypes library
--> 110         self._lib = N.ctypeslib.load_library('libtsnecuda', self._path) # Load the ctypes library
    111 
    112         # Hook the BH T-SNE function

~/.local/lib/python3.6/site-packages/numpy/ctypeslib.py in load_library(libname, loader_path)
    150             if os.path.exists(libpath):
    151                 try:
--> 152                     return ctypes.cdll[libpath]
    153                 except OSError:
    154                     ## defective lib file

/usr/lib/python3.6/ctypes/__init__.py in __getitem__(self, name)
    421 
    422     def __getitem__(self, name):
--> 423         return getattr(self, name)
    424 
    425     def LoadLibrary(self, name):

/usr/lib/python3.6/ctypes/__init__.py in __getattr__(self, name)
    416         if name[0] == '_':
    417             raise AttributeError(name)
--> 418         dll = self._dlltype(name)
    419         setattr(self, name, dll)
    420         return dll

/usr/lib/python3.6/ctypes/__init__.py in __init__(self, name, mode, handle, use_errno, use_last_error)
    346 
    347         if handle is None:
--> 348             self._handle = _dlopen(self._name, mode)
    349         else:
    350             self._handle = handle

OSError: /home/abhi/.local/lib/python3.6/site-packages/tsnecuda/libtsnecuda.so: undefined symbol: _ZN5faiss14FaissExceptionC1ERKSsPKcS4_i
```

**Comment by abhii-p** [comment]
> We have had ongoing issues trying to get this code working with conda. One way to fix this is to point to the libfaiss.so using the LD_LIBRARY_PATH. You should also be able to build the project from source (I would use the fit_tsne branch), which could decrease the painful overhead of making it work. We're working on getting these conda issues resolved, but it's slow going.

Thank you for responding. I have set the path using `export LD_LIBRARY_PATH="/usr/local/lib"` then I get an other error `undefined symbol` when executing `tsnecuda`. 


```
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-2-e5f7bd09822d> in <module>
     13     tsne = TSNE(n_components=2, perplexity=i,
     14                 learning_rate=200,
---> 15                 n_iter=j)
     16     tsne_data = tsne.fit_transform(x_scaled[:20000, :])
     17     tsne_df[f'Type: {i}_{j}'] = pd.DataFrame(np.vstack([tsne_data.T, y]).T, 

~/.local/lib/python3.6/site-packages/tsnecuda/TSNE.py in __init__(self, n_components, perplexity, early_exaggeration, learning_rate, num_neighbors, force_magnify_iters, pre_momentum, post_momentum, theta, epssq, n_iter, n_iter_without_progress, min_grad_norm, perplexity_epsilon, metric, init, return_style, num_snapshots, verbose, random_seed, use_interactive, viz_timeout, viz_server, dump_points, dump_file, dump_interval, print_interval, device)
    108         # self._faiss_lib = N.ctypeslib.load_library('libfaiss', self._path) # Load the ctypes library
    109         # self._gpufaiss_lib = N.ctypeslib.load_library('libgpufaiss', self._path) # Load the ctypes library
--> 110         self._lib = N.ctypeslib.load_library('libtsnecuda', self._path) # Load the ctypes library
    111 
    112         # Hook the BH T-SNE function

~/.local/lib/python3.6/site-packages/numpy/ctypeslib.py in load_library(libname, loader_path)
    150             if os.path.exists(libpath):
    151                 try:
--> 152                     return ctypes.cdll[libpath]
    153                 except OSError:
    154                     ## defective lib file

/usr/lib/python3.6/ctypes/__init__.py in __getitem__(self, name)
    421 
    422     def __getitem__(self, name):
--> 423         return getattr(self, name)
    424 
    425     def LoadLibrary(self, name):

/usr/lib/python3.6/ctypes/__init__.py in __getattr__(self, name)
    416         if name[0] == '_':
    417             raise AttributeError(name)
--> 418         dll = self._dlltype(name)
    419         setattr(self, name, dll)
    420         return dll

/usr/lib/python3.6/ctypes/__init__.py in __init__(self, name, mode, handle, use_errno, use_last_error)
    346 
    347         if handle is None:
--> 348             self._handle = _dlopen(self._name, mode)
    349         else:
    350             self._handle = handle

OSError: /home/abhi/.local/lib/python3.6/site-packages/tsnecuda/libtsnecuda.so: undefined symbol: _ZN5faiss14FaissExceptionC1ERKSsPKcS4_i
```

**Comment by rmrao** [comment]
Just updated the conda binaries for CUDA 9.0. You can install with `conda install tsnecuda cuda90 -c cannylab`. Hopefully this fixes your issue.

**Comment by abhiagwl4262** [comment]
> > We have had ongoing issues trying to get this code working with conda. One way to fix this is to point to the libfaiss.so using the LD_LIBRARY_PATH. You should also be able to build the project from source (I would use the fit_tsne branch), which could decrease the painful overhead of making it work. We're working on getting these conda issues resolved, but it's slow going.
> 
> Thank you for responding. I have set the path for libfaiss.so using `export LD_LIBRARY_PATH="/usr/local/lib"` then I get an other error `undefined symbol` when executing `tsnecuda`.
> 
> ```
> ---------------------------------------------------------------------------
> OSError                                   Traceback (most recent call last)
> <ipython-input-2-e5f7bd09822d> in <module>
>      13     tsne = TSNE(n_components=2, perplexity=i,
>      14                 learning_rate=200,
> ---> 15                 n_iter=j)
>      16     tsne_data = tsne.fit_transform(x_scaled[:20000, :])
>      17     tsne_df[f'Type: {i}_{j}'] = pd.DataFrame(np.vstack([tsne_data.T, y]).T, 
> 
> ~/.local/lib/python3.6/site-packages/tsnecuda/TSNE.py in __init__(self, n_components, perplexity, early_exaggeration, learning_rate, num_neighbors, force_magnify_iters, pre_momentum, post_momentum, theta, epssq, n_iter, n_iter_without_progress, min_grad_norm, perplexity_epsilon, metric, init, return_style, num_snapshots, verbose, random_seed, use_interactive, viz_timeout, viz_server, dump_points, dump_file, dump_interval, print_interval, device)
>     108         # self._faiss_lib = N.ctypeslib.load_library('libfaiss', self._path) # Load the ctypes library
>     109         # self._gpufaiss_lib = N.ctypeslib.load_library('libgpufaiss', self._path) # Load the ctypes library
> --> 110         self._lib = N.ctypeslib.load_library('libtsnecuda', self._path) # Load the ctypes library
>     111 
>     112         # Hook the BH T-SNE function
> 
> ~/.local/lib/python3.6/site-packages/numpy/ctypeslib.py in load_library(libname, loader_path)
>     150             if os.path.exists(libpath):
>     151                 try:
> --> 152                     return ctypes.cdll[libpath]
>     153                 except OSError:
>     154                     ## defective lib file
> 
> /usr/lib/python3.6/ctypes/__init__.py in __getitem__(self, name)
>     421 
>     422     def __getitem__(self, name):
> --> 423         return getattr(self, name)
>     424 
>     425     def LoadLibrary(self, name):
> 
> /usr/lib/python3.6/ctypes/__init__.py in __getattr__(self, name)
>     416         if name[0] == '_':
>     417             raise AttributeError(name)
> --> 418         dll = self._dlltype(name)
>     419         setattr(self, name, dll)
>     420         return dll
> 
> /usr/lib/python3.6/ctypes/__init__.py in __init__(self, name, mode, handle, use_errno, use_last_error)
>     346 
>     347         if handle is None:
> --> 348             self._handle = _dlopen(self._name, mode)
>     349         else:
>     350             self._handle = handle
> 
> OSError: /home/abhi/.local/lib/python3.6/site-packages/tsnecuda/libtsnecuda.so: undefined symbol: _ZN5faiss14FaissExceptionC1ERKSsPKcS4_i
> ```

I am having the same issue when tsne-cuda installed from sources.

**Comment by abhiagwl4262** [comment]
> Just updated the conda binaries for CUDA 9.0. You can install with `conda install tsnecuda cuda90 -c cannylab`. Hopefully this fixes your issue.

I have tried this as well. Not working for me.

**Comment by rmrao** [comment]
Please open a new issue and describe the steps you have taken and the error message you are getting, as well as providing basic info (OS version, etc).

**Comment by makimon123** [comment]
How did you solve this problem? Your help is very much needed！
