### ISSUE TITLE
can this be run on windows?

### ISSUE THREAD

**Issue by Sandy4321** [CannyLab/tsne-cuda#32]
can this be run on windows?

**Comment by p3732** [comment]
The FAISS library this builds on does not support Windows ATM, most likely no.

**Comment by DavidMChan** [comment]
No, this does not officially support windows. It's possible that it could be compiled for windows, but I've never tried, so there's probably issues with our upstream dependencies (such as FAISS)

**Comment by rmrao** [comment]
Closing as answered.
