### ISSUE TITLE
projection to other than 2 dimension error

### ISSUE THREAD

**Issue by pobingwanghai** [CannyLab/tsne-cuda#35]
import numpy as np
from tsnecuda import TSNE
X = np.array([[0, 0, 0], [0, 1, 1], [1, 0, 1], [1, 1, 1]])
X_embedded = TSNE(method='naive', n_components=10).fit_transform(X)
X_embedded.shape

the above is the code from the basic usage, below is the error report

TypeError                                 Traceback (most recent call last)
<ipython-input-6-0d40d845a584> in <module>
      2 from tsnecuda import TSNE
      3 X = np.array([[0, 0, 0], [0, 1, 1], [1, 0, 1], [1, 1, 1]])
----> 4 X_embedded = TSNE(method='naive', n_components=10).fit_transform(X)
      5 X_embedded.shape

TypeError: __init__() got an unexpected keyword argument 'method'

**Comment by DavidMChan** [comment]
The 'naive' method is likely broken - see #3. Currently the only supported code is the projection into two dimensions with FIT-SNe or Barnes-Hut.
