### ISSUE TITLE
I encounter strange output when use this tsne to visualize data.

### ISSUE THREAD

**Issue by HelloRicky123** [CannyLab/tsne-cuda#37]
Hi sir,

To be honest I don't really understand how tsne do. I just use the code bellow to visualize my feature gotten by CNN. The feature is a numpy array with dimension of n * 9216(n * 6x6x256). 

tsne_point = TSNE().fit_transform(feature)

Then it first print message as "WARNING clustering 430 points to 20 centroids: please provide at least 780 training points". Then it print a lot of lines like below, about 430 * 6 lines totally.

Can anyone help me? Thanks a lot!

578, -1
578, -1
578, -1
578, -1
578, -1
578, -1
570, -1
570, -1
570, -1
570, -1
570, -1
570, -1
585, -1
585, -1
585, -1
585, -1
585, -1
585, -1
576, -1
576, -1
576, -1

**Comment by rmrao** [comment]
The centroid warning can be safely ignored, it just says that you’re not providing enough points for maximum efficiency.

The -1 output is related to a bug in the master branch. You can check out the fit_tsne branch, which uses a different implementation and doesn’t have this bug.

We hope to merge fit_tsne to master and put that on conda eventually. Unfortunately this isn’t a main project for any of us, so it really just depends on one of us finding the time to do it.

**Comment by rmrao** [comment]
Since there's no response from original poster, I'm assuming this is fixed and closing.
