### ISSUE TITLE
Connection Failed

### ISSUE THREAD

**Issue by ShellingFord221** [CannyLab/tsne-cuda#38]
Hi, I use the recommended installation of conda, but there is a HTTP 000 connection error:
![image](https://user-images.githubusercontent.com/40685673/59198518-8143cb00-8bc6-11e9-82bf-1e673998a88c.png)
I have tried several times, but this error always occurs. 
What should I do? Thanks!

**Comment by ShellingFord221** [comment]
I found that my computer (not the server) can download the bz2 file from the url given above. How can I install tsnecuda from local file?

**Comment by rmrao** [comment]
>  conda can also be called with a list of explicit conda package filenames
    (e.g. ./lxml-3.2.0-py27_0.tar.bz2). Using conda in this mode implies the
    --no-deps option, and should likewise be used with great caution. Explicit
    filenames and package specifications cannot be mixed in a single command.

Type `conda install -h` and follow directions.

Closing because this is a conda issue not a tsnecuda issue.
