### ISSUE TITLE
Link to Arxiv paper

### ISSUE THREAD

**Issue by impredicative** [CannyLab/tsne-cuda#4]
Kindly add a link to your Arxiv paper in your readme:

https://arxiv.org/abs/1807.11824

**Comment by rmrao** [comment]
Added!

**Comment by impredicative** [comment]
It is IMO preferable to link to the web page version of the page, and never to the PDF file directly. Some people only want to read the abstract in the web page. Thanks.

**Comment by rmrao** [comment]
Fair enough, will edit.

**Comment by impredicative** [comment]
Why link to the the versioned articled (v1)? Do you anticipate that if there is a v2, it won't correspond to this implementation?

**Comment by rmrao** [comment]
No, I just wasn’t paying attention and copied/pasted the versioned link instead of the non-versioned link
