### ISSUE TITLE
GLIB2.27 error

### ISSUE THREAD

**Issue by abinashsinha330** [CannyLab/tsne-cuda#41]
Ubuntu16.04
Python3.6.8

Getting this error while running tsnecuda:

tsne_model = TSNE(n_iter=2500)
  File "/home/abinashsinha330/anaconda3/lib/python3.6/site-packages/tsnecuda/TSNE.py", line 110, in __init__
    self._lib = N.ctypeslib.load_library('libtsnecuda', self._path) # Load the ctypes library
  File "/home/abinashsinha330/anaconda3/lib/python3.6/site-packages/numpy/ctypeslib.py", line 150, in load_library
    return ctypes.cdll[libpath]
  File "/home/abinashsinha330/anaconda3/lib/python3.6/ctypes/__init__.py", line 423, in __getitem__
    return getattr(self, name)
  File "/home/abinashsinha330/anaconda3/lib/python3.6/ctypes/__init__.py", line 418, in __getattr__
    dll = self._dlltype(name)
  File "/home/abinashsinha330/anaconda3/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
**OSError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by /home/abinashsinha330/anaconda3/lib/python3.6/site-packages/tsnecuda/libtsnecuda.so)**

I checked my cuda version if 10.0.130 so I used the command:
"conda install tsnecuda cuda100 -c cannylab" for installing tsnecuda

I have glib version of 2.23 in Ubuntu16.04. Please help me with the same

**Comment by pobingwanghai** [comment]
I get the same error.

**Comment by pobingwanghai** [comment]
@abinashsinha330 if we use the conda install, it seems we have to use the ubuntu 18.04. But i haven't check whether install from the binary will get this problem.

**Comment by DavidMChan** [comment]
We built the conda binaries with Ubuntu 18.04, so unfortunately it seems like they were linked against a newer glibc version than we intended. Building from source should not have this issue while we try to compile against an earlier version of the C library. 

Another option if you are set on using the conda build is to install an updated version of GLIBC side-by-side with your current version.

**Comment by abinashsinha330** [comment]
@DavidMChan let me try the latter one and see if everything works out... Thanks for the quick response...

**Comment by abinashsinha330** [comment]
This is the error I get after running **make install** command after following the steps to install glib-2.27 on my Ubuntu16.04 which has by default glib2.23.

mkdir: cannot create directory '/opt/glibc-2.27': Permission denied
Makerules:1034: recipe for target '/opt/glibc-2.27/lib/libc.a' failed
make[1]: *** [/opt/glibc-2.27/lib/libc.a] Error 1
make[1]: Leaving directory '/mnt/glibc-2.27'
Makefile:12: recipe for target 'install' failed
make: *** [install] Error 2

**Comment by DavidMChan** [comment]
If you're installing in opt, then by default you will need sudo permissions. see: `mkdir: cannot create directory '/opt/glibc-2.27': Permission denied`

**Comment by abinashsinha330** [comment]
I installed it now... But now when I check the glibc version installed using comman, "ldd --version", I get **Segmentation fault (core dumped)**

**Comment by abinashsinha330** [comment]
It gives segmentation fault (core dumped) error after I run the export command as suggested in the link. Is it because there is confusion occurring due to two version of glibc?

**Comment by pobingwanghai** [comment]
@abinashsinha330 @DavidMChan After finishing the install, I get the same error. Besides, i am worried whether update the new libc will influence the installed packages

**Comment by DavidMChan** [comment]
If you installed it properly, both versions should be able to be resident at once, however this is more of a hack, then an actual fix. I recommend compiling from source, which is much more likely to fix the problem.

**Comment by rmrao** [comment]
Also I am trying to fix the issue in the conda build - there’s apparently a whole section in the conda build documentation on specifically this issue and cmake so it’s plausible it may take a bit before I have it all figured out.

**Comment by pobingwanghai** [comment]
@rmrao thank you, I will try to build from the binary and i notice that the version you update to the conda on 11.6.2019 works ok.

**Comment by pobingwanghai** [comment]
I have tried to build from the binary source and the tsnecuda works fine with both python 3.6, 3.7 and cuda 9 and cuda 10.

**Comment by abinashsinha330** [comment]
@DavidMChan actually I do not have that much experience working in linux libraries... I think I will have to build from source and try once...

**Comment by abinashsinha330** [comment]
Let me try installing using binaries and get back to you.

**Comment by abinashsinha330** [comment]
I have multiple Python versions installed in my system and default is Python2.7.12. I am doing my development using Python venv based on Python3.6.4. Is there a way to enable building process using custom Python version I have installed for usage?

**Comment by abinashsinha330** [comment]
While running the command (Also it is using the default Python 2.7.12 version of Ubuntu16.04 for creating Python bindings. How to make it using my custom Python 3.6.4 version which I installed for creating Python bindings:
**cmake .. -DBUILD_PYTHON=TRUE -DWITH_ZMQ=TRUE -DBUILD_TEST=TRUE -DWITH_ZMQ=TRUE**


-- Not building standalone gpufaiss lib. To build gpufaiss standalone use -DWITH_FAISS_GPU_STANDALONE=ON
-- Found OpenBLAS libraries: /usr/lib/libopenblas.so
-- Found OpenBLAS include: /usr/include
CMake Warning at third_party/glog/CMakeLists.txt:49 (find_package):
  By not providing "Findgflags.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "gflags", but
  CMake did not find one.

  Could not find a package configuration file provided by "gflags" (requested
  version 2.2.0) with any of the following names:

    gflagsConfig.cmake
    gflags-config.cmake

  Add the installation prefix of "gflags" to CMAKE_PREFIX_PATH or set
  "gflags_DIR" to a directory containing one of the above files.  If "gflags"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Found OpenBLAS libraries: /usr/lib/libopenblas.so
-- Found OpenBLAS include: /usr/include
CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR
  GTEST_MAIN_LIBRARY)
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.5/Modules/FindGTest.cmake:205 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  third_party/faiss/tests/CMakeLists.txt:7 (find_package)

**Comment by abinashsinha330** [comment]
To stop the above error, I turned -DBUILD_TEST=FALSE. Now **cmake** command was successfully executed. Now while doing **make**, I get the below issue:

-- Not building standalone gpufaiss lib. To build gpufaiss standalone use -DWITH_FAISS_GPU_STANDALONE=ON
-- Found OpenBLAS libraries: /usr/lib/libopenblas.so
-- Found OpenBLAS include: /usr/include
CMake Warning at third_party/glog/CMakeLists.txt:49 (find_package):
  By not providing "Findgflags.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "gflags", but
  CMake did not find one.

  Could not find a package configuration file provided by "gflags" (requested
  version 2.2.0) with any of the following names:

    gflagsConfig.cmake
    gflags-config.cmake

  Add the installation prefix of "gflags" to CMAKE_PREFIX_PATH or set
  "gflags_DIR" to a directory containing one of the above files.  If "gflags"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Found OpenBLAS libraries: /usr/lib/libopenblas.so
-- Found OpenBLAS include: /usr/include
-- Not building tests. To build tests use -DBUILD_TEST=ON
-- Configuring done
-- Generating done
-- Build files have been written to: /mnt/tsne-cuda/build
[  9%] Built target faiss
[ 12%] Built target glog
[ 13%] Built target gtest
[ 13%] Building NVCC (Device) object CMakeFiles/tsne.dir/src/tsne_generated_fit_tsne.cu.o
/mnt/tsne-cuda/src/fit_tsne.cu(314): error: name followed by "::" must be a class or namespace name

/mnt/tsne-cuda/src/fit_tsne.cu(314): error: expected a ";"

/mnt/tsne-cuda/src/fit_tsne.cu(315): error: name followed by "::" must be a class or namespace name

/mnt/tsne-cuda/src/fit_tsne.cu(315): error: expected a ";"

/mnt/tsne-cuda/src/fit_tsne.cu(321): error: identifier "publisher" is undefined

/mnt/tsne-cuda/src/fit_tsne.cu(321): error: identifier "ZMQ_RCVTIMEO" is undefined

/mnt/tsne-cuda/src/fit_tsne.cu(322): error: identifier "ZMQ_SNDTIMEO" is undefined

/mnt/tsne-cuda/src/fit_tsne.cu(332): error: name followed by "::" must be a class or namespace name

/mnt/tsne-cuda/src/fit_tsne.cu(332): error: expected a ";"

/mnt/tsne-cuda/src/fit_tsne.cu(333): error: identifier "request" is undefined

/mnt/tsne-cuda/src/fit_tsne.cu(475): error: name followed by "::" must be a class or namespace name

/mnt/tsne-cuda/src/fit_tsne.cu(475): error: expected a ";"

/mnt/tsne-cuda/src/fit_tsne.cu(476): error: identifier "message" is undefined

/mnt/tsne-cuda/src/fit_tsne.cu(478): error: identifier "publisher" is undefined

/mnt/tsne-cuda/src/fit_tsne.cu(479): error: name followed by "::" must be a class or namespace name

/mnt/tsne-cuda/src/fit_tsne.cu(479): error: expected a ";"

/mnt/tsne-cuda/src/fit_tsne.cu(480): error: identifier "request" is undefined

17 errors detected in the compilation of "/tmp/tmpxft_0000483a_00000000-12_fit_tsne.compute_70.cpp1.ii".
CMake Error at tsne_generated_fit_tsne.cu.o.cmake:262 (message):
  Error generating file
  /mnt/tsne-cuda/build/CMakeFiles/tsne.dir/src/./tsne_generated_fit_tsne.cu.o


CMakeFiles/tsne.dir/build.make:45885: recipe for target 'CMakeFiles/tsne.dir/src/tsne_generated_fit_tsne.cu.o' failed
make[2]: *** [CMakeFiles/tsne.dir/src/tsne_generated_fit_tsne.cu.o] Error 1
CMakeFiles/Makefile2:69: recipe for target 'CMakeFiles/tsne.dir/all' failed
make[1]: *** [CMakeFiles/tsne.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by rmrao** [comment]
Tests and ZMQ both will not compile unfortunately. They were added a long time ago and no one has had the time to update them. So you should really just do `cmake ..` without changing the specifics.

We don't ever actually compile against python headers, so you really shouldn't have any version issues? The only time python gets invoked is at the end when you go to `build/python` and run `pip install -e .`. If this is not installing in the correct location, make sure that `pip` points to your virtualenv correctly.

**Comment by abinashsinha330** [comment]
yeah I figured it out seeing the code.... I am doing that now...

**Comment by rmrao** [comment]
Also FYI if you know what GPU you have and you look up the compute capability, you can go to `CMakeLists.txt` and look at the lines that read `sm_30,...`, `sm_60...`, and delete all lines that don't correspond to your compute capability. By default it tries to compile for all GPUs which basically multiplies compile time by 6x. (This may also fix bugs with parallel compilation)

If you need to iterate on this multiple times for debugging then this can save you a lot of time.

**Comment by abinashsinha330** [comment]
Yeah I checked that already. Thanks

**Comment by abinashsinha330** [comment]
For 400,000 128-D embedding vectors should it take more than a day to generate the visualization? I might be wrong...  Just wanted to check with you once...

**Comment by abinashsinha330** [comment]
I got different visualizations for the same embedding vectors indicating altogether different distributions of data when running once using multi-core and your version of tSNE algorithm...

**Comment by rmrao** [comment]
So there was a bug with the way we handled early exaggeration (see #42). It's in the process of being debugged, but a fix for some of the issues identified was pushed in #45.

**Comment by abinashsinha330** [comment]
so I will have to take checkout this latest code and try once again? Just missed checking out that fixed code I guess... I think my issue is also due to the fact that I have a lot of data too but I think I won't have the noise situation like mentioned in the last comment of #42

**Comment by abinashsinha330** [comment]
I had checked out the code yesterday so I guess it has the version of the code in which you gave fix for passing of early exaggeration... correct me if I am wrong?

**Comment by abinashsinha330** [comment]
I checked I have build the fixed version... Let me play with different hyper-parameters and see if I find any improvement. So, my data has around 410k rows each being 128-D.

**Comment by abinashsinha330** [comment]
![tSNEcuda_final_AB_0](https://user-images.githubusercontent.com/8405367/59722389-67167800-91d8-11e9-91b7-3aa7192a410f.png)


![tSNE_final_AB_0](https://user-images.githubusercontent.com/8405367/59722403-6da4ef80-91d8-11e9-827b-7c527e1145cc.png)

**Comment by DavidMChan** [comment]
This difference should be addressed by the fix for #42 , I'm going to close this, but feel free to reopen it if you have additional issues!
