### ISSUE TITLE
Keep old version available on Conda

### ISSUE THREAD

**Issue by cciccole** [CannyLab/tsne-cuda#43]
It seems that the old version of this package is not available on Conda anymore? Let me know if I'm mistaken.

I now have some environments that aren't reproducible as a result. It's a good practice (and somewhat a main feature of Conda) to have all major versions available. Maybe you have a good reason not to, though.

Related: #42

**Comment by rmrao** [comment]
ack sorry - was a mistake to delete them.

I've reuploaded the CUDA 9.0 version. I may not have the other versions easily available. You can install this one with `conda install tsnecuda==0.2.1 -c cannylab`. If you need a different version... I can try to recompile the old version or see if I have the original file lying around.

Sorry again - I'm not very familiar with the conda build process and messed up.

**Comment by cciccole** [comment]
Thanks. Besides cuda version I think the bigger concern right now is actual builds of the code corresponding at least to your github releases. Maybe you can't do it immediately, but I think those should be rebuilt and put on conda. Unless you have some reason to fully eliminate the old versions of this package?

Also, as an aside, this package is some amazing work!  CC @DavidMChan @huang4fstudio. Very impressive.

**Comment by rmrao** [comment]
It's a bit of an annoyance because conda seems to have an issue with multi-threaded compiling of CUDA code and `nvcc` is just really slow... Which means each build for each CUDA version can take 8+ hours (especially since we're building for multiple GPU architectures). This is especially frustrating when there are issues with the conda builds, because it can take that long between iterations to debug.

@DavidMChan maybe you have the old files around? The one I uploaded does correspond to the previous release, but only for CUDA9.0.

**Comment by rmrao** [comment]
As an aside there's also a `bh_tsne` branch which is the old version still up - so if anyone wants to recompile the old version you can checkout that branch instead of digging through the git history.

**Comment by rmrao** [comment]
Oh and apparently in the previous release we called the github release version 1.0 but put it up on conda as version 0.2.1. I have no idea why we did this.

**Comment by cciccole** [comment]
> Oh and apparently in the previous release we called the github release version 1.0 but put it up on conda as version 0.2.1. I have no idea why we did this.

Ah, okay. So it is the former build of tsnecuda that used to be on conda, but the only option is cuda9.0. Thanks for putting it back up. I'm personally in no need of the other versions because I was using 9.0, but it's possible others were affected.

To clarify this further, does this former conda build correspond to the `V1` tag on master, or to the current state of the `bh_tsne` branch, which is ahead of V1?

**Comment by rmrao** [comment]
It corresponds to the `V1` tag. the `bh_tsne` branch has a handful of minor fixes, but is fundamentally the same as the `V1` tag.
