### ISSUE TITLE
Still have parallel compilation issues

### ISSUE THREAD

**Issue by rmrao** [CannyLab/tsne-cuda#46]
There are parallel compilation issues in the conda build process, and some were noted in issue #42.

One string possibility is that when I compile the code on my machine I usually disable compilation for GPU architectures other than my actual GPU architecture. This is not done (obviously) during conda-build as we want to build for all architectures. I also suspect most users won't try this since we don't have an option to do so (you just have to delete them from the `CMakeLists.txt` file).

**Comment by DavidMChan** [comment]
This is fixed in the dev branch, and will be merged pending #81
