### ISSUE TITLE
install error using pip 

### ISSUE THREAD

**Issue by LeZhengThu** [CannyLab/tsne-cuda#5]
When I tried to install tsne-cuda using 'pip install tsne-cuda', it threw out the error:

Could not find a version that satisfies the requirement tsne-cuda (from versions: )
No matching distribution found for tsne-cuda

**Comment by DavidMChan** [comment]
There was a bug in our readme which has now been updated, the package is "tsnecuda" not "tsne-cuda". The pypi link is here: https://pypi.org/project/tsnecuda/0.1.1/
