### ISSUE TITLE
PackagesNotFoundError

### ISSUE THREAD

**Issue by vichu-kumar5** [CannyLab/tsne-cuda#50]
Collecting package metadata (current_repodata.json): done
Solving environment: failed
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - tsnecuda -> libgfortran
  - tsnecuda -> *[track_features=cuda91]

Current channels:

  - https://conda.anaconda.org/cannylab/linux-64
  - https://conda.anaconda.org/cannylab/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

I tried installing tsnecuda on colab using : 
!conda install tsnecuda cuda100 -c cannylab. 

Have been receiving this error since 12:00 PM IST 8th July,2019.  Was working fine 1-2 weeks ago. (I work on a temp virtual env setup on Colab using miniconda)

!conda install cuda100 -c cannylab is working fine. No errors.

**Comment by rmrao** [comment]
There seems to have been an update to conda-build recently which possibly broke things. We're building version 2.1 so once we post that it should fix this issue.

**Comment by rmrao** [comment]
This should be fixed now, just tested them all. If you had previously installed tsnecuda it is possible you may need to create a new environment. I'm going to close this - if you still have issues feel free to reopen or create a new issue.

**Comment by ulyssesp** [comment]
This is not fixed with conda version 4.7.11

**Comment by DavidMChan** [comment]
@ulyssesp  - Can you open a new issue with a bit of information on the exact errors that you are getting, how you got them, and the environment that you are using (machine, OS, conda env)? We are having no issues validating the install on our machines.

**Comment by ulyssesp** [comment]
Sorry for opening - realized you don't support windows.
