### ISSUE TITLE
windows installation

### ISSUE THREAD

**Issue by shidaide2016** [CannyLab/tsne-cuda#55]
So at this time this cuda-accelerated tsne id not supported on windows ? I've tried on my PC but met errors when I was using mkl installed by anaconda.

**Comment by DavidMChan** [comment]
We have no plans to support a windows build at this time. You are welcome to submit a PR to add this functionality.

**Comment by MikeTkachuk** [comment]
https://github.com/CannyLab/tsne-cuda/pull/130 should add some support
