### ISSUE TITLE
tsne-cuda appears to kill jupyter kernel

### ISSUE THREAD

**Issue by Tobychev** [CannyLab/tsne-cuda#57]
I've managed to get tsnecuda to work in a terminal session using ipython, and it runs fine as far as I can tell (~1.7 s on 13k rows), but when I try using it via a jupyter notebook, the jupyter kernel invariably gets restarted after a few seconds. 

I can't actually tell why, I just get a message that the kernel seems hanged and has been restarted. It might be related to qt not being accessible in the expected way when using a notebook, which I base on me having problems with using tsne-cuda in the terminal due to problems with the qt install. I have however resolved these problems but the jupyter notebook keeps dying whenever I try a fit_transform call.

**Comment by rmrao** [comment]
Can you add a gist or upload a file that causes this?

**Comment by Tobychev** [comment]
No, when I tried making a small example it of course worked and I couldn't get it to break again :(

Since the tsne works fine with the data if I run in a terminal, the problem has something to do with the complete environment in that particular notebook, I'll come back and reopen this if I manage to create more notebooks that crash and can find some commonality.
