### ISSUE TITLE
Funtionality request: Cluster member retrieval

### ISSUE THREAD

**Issue by onurctirtir** [CannyLab/tsne-cuda#58]
As I see, there is no function to retrieve the members of 'clusters'. If I am not wrong, would you consider to add such a functionality to TSNE class ?

**Comment by rmrao** [comment]
TSNE is a dimensionality reduction algorithm not a clustering algorithm. There are a number of perfectly good and fast clustering algorithms available in e.g. scikit-learn (see [sklearn.cluster](https://scikit-learn.org/stable/modules/classes.html#module-sklearn.cluster)). As such it's not clear what benefit including this in the TSNE class itself would provide.
