### ISSUE TITLE
Faiss assertion 'err == cudaSuccess' failed

### ISSUE THREAD

**Issue by woolpeeker** [CannyLab/tsne-cuda#60]
I use conda installation, with cuda100 tsnecuda=2.0.0
I have multiple GPUs, and I want to use the second one.

lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial

`import numpy as np
from tsnecuda import TSNE

x = np.zeros([100,100])

tsne = TSNE(n_components=2, init='random', perplexity=80,
           device=1)

t_x = tsne.fit_transform(x)`
result in

Faiss assertion 'err == cudaSuccess' failed in faiss::gpu::StackDeviceMemory::Stack::Stack(int, size_t) at /home/root/miniconda/conda-bld/tsnecuda_1563315098013/work/third_party/faiss/gpu/utils/StackDeviceMemory.cpp:33
Aborted (core dumped)

**Comment by DavidMChan** [comment]
Thanks for reporting this - I don't seem to encounter this issue on my machine with the code you have provided (Note that using all zeros as the input will produce NaN values in the fit_transform). Which GPUs are you using, and which version of CUDA/CUDA Drivers?

**Comment by woolpeeker** [comment]
Thanks for replying. I test my code today, and it works well. I still cannot figure why if fails before. I will close this issue anyway. Thanks again.
