### ISSUE TITLE
CUDA_cublas_device_LIBRARY is NOTFOUND with Ubuntu 18.04/CUDA 10.1

### ISSUE THREAD

**Issue by jmcorgan** [CannyLab/tsne-cuda#61]
Hopefully this is not a duplicate or covered elsewhere, but I'm having a difficult time compiling from a github clone.

In short, 'cmake ..' fails with the following error message:

```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CUDA_cublas_device_LIBRARY (ADVANCED)
    linked by target "tsnecuda" in directory /opt/dev/clabs/src/tsne-cuda
    linked by target "tsne" in directory /opt/dev/clabs/src/tsne-cuda

-- Configuring incomplete, errors occurred!
```

The system is Ubuntu 18.04, CUDA tools are 10.1.243 (from Nvidia site), gcc is 7.4.0, cmake is 3.10.2.

As far as I can tell the rest of the CUDA toolkit is found okay. I have added the relevant /usr/local/cuda/* directories to PATH, LD_LOAD_LIBRARY, and LD_LIBRARY_PATH.

Before I dig any further, is this a known issue with a known resolution?

**Comment by DavidMChan** [comment]
I believe this is an issue with the newer CUDA libraries (which move cublas out of /use/local/cuda) and CMAKE 3.10. updating cmake to a later version (3.12 or higher) should fix the issue.

**Comment by jmcorgan** [comment]
Excellent, thanks for the quick response, you've probably saved me hours of time.

**Comment by jmcorgan** [comment]
...and it worked. Grabbed cmake 3.15.2, compiled, used that for tsne-cuda, got through the cmake step and it's now compiling.

**Comment by jmcorgan** [comment]
Success. Thanks again for the help.
```
In [2]: tsnecuda.test()
Initializing cuda handles... done.
KNN Computation... done.
Computing Pij matrix... done.
Initializing low dim points... done.
Initializing CUDA memory... done.
[Step 0] Avg. Gradient Norm: 5.6306e-05
[Step 10] Avg. Gradient Norm: 2.68145e-06
[Step 20] Avg. Gradient Norm: 1.37306e-07
Reached minimum gradient norm: 7.31604e-08
_time_initialization: 0.635964s
_time_knn: 0.093609s
_time_symmetry: 0.038884s
_time_init_low_dim: 0.000323s
_time_init_fft: 0.317806s
_time_compute_charges: 2.5e-05s
_time_precompute_2d: 0.003014s
_time_nbodyfft: 0.003323s
_time_norm: 0.00074s
_time_attr: 0.001056s
_time_apply_forces: 0.002083s
_time_other: 0.000364s
total_time: 1.09719s
```
