### ISSUE TITLE
OSError: no file with expected extension error

### ISSUE THREAD

**Issue by Ryan-P-P** [CannyLab/tsne-cuda#62]
### **[OS Version]**
Ubuntu 16.04.5 LTS

### **[GPU version]**
nvcc: NVIDIA (R) Cuda compiler driver
Cuda compilation tools, release 10.0, V10.0.130

### **[method of installation]**
1. download your github zip file 
2. unzip and move file to my linux server
3. python tsne-cuda-master/src/python/setup.py install

### **[code]**
import tsnecuda
tsnecuda.test()

### **[output]**
/usr/local/lib/python3.5/dist-packages/tsnecuda-2.0.0-py3.5.egg/tsnecuda/__init__.py in test()
      5     import numpy as np
      6     X = np.random.random((5000, 50))
----> 7     TSNE(verbose=1).fit_transform(X)

/usr/local/lib/python3.5/dist-packages/tsnecuda-2.0.0-py3.5.egg/tsnecuda/TSNE.py in __init__(self, n_components, perplexity, early_exaggeration, learning_rate, num_neighbors, force_magnify_iters, pre_momentum, post_momentum, theta, epssq, n_iter, n_iter_without_progress, min_grad_norm, perplexity_epsilon, metric, init, return_style, num_snapshots, verbose, random_seed, use_interactive, viz_timeout, viz_server, dump_points, dump_file, dump_interval, print_interval, device, magnitude_factor)

--> 126         self._lib = N.ctypeslib.load_library('libtsnecuda', self._path)  # Load the ctypes library

/usr/local/lib/python3.5/dist-packages/numpy/ctypeslib.py in load_library(libname, loader_path)
--> 155         raise OSError("no file with expected extension")

OSError: no file with expected extension

**Comment by DavidMChan** [comment]
Our code cannot just be compiled with `setup.py install`. as it relies on some C binaries which are compiled with nvcc. Please follow the installation instructions here: https://github.com/CannyLab/tsne-cuda/wiki/Installation
