### ISSUE TITLE
“Device warp size not supported” error even with test()

### ISSUE THREAD

**Issue by benfry** [CannyLab/tsne-cuda#66]
Saw the same error in [this issue](https://github.com/CannyLab/tsne-cuda/issues/33), but that dealt with multiple processes—I'm getting the error even with `tsnecuda.test()`. 

* Did an install from scratch with a just-downloaded CUDA 10.1 from NVIDIA 
* Hit [this issue](https://github.com/CannyLab/tsne-cuda/issues/61) with `CUDA_cublas_device_LIBRARY is NOTFOUND` but fixed it by following the recommendation there to install a newer `cmake`. (Thanks!)

But once everything was built:

```
cd python
python3
>>> import tsnecuda
>>> tsnecuda.test()
```

produced:

```
E: Device warp size not supported.
```

Any thoughts? Possibly a GPU that's too lame? (This is a GeForce GTX 980 Ti 6GB) Is there a specific NVIDIA driver I should be using?

Thanks for any thoughts!

**Comment by benfry** [comment]
Aaaand… rebooting solved the problem. I hate the computers.

Turns out that installing the CUDA packages messes with the drivers a bit, which I noticed after running `nvidia-smi` and getting another error: `Failed to initialize NVML: Driver/library version mismatch`.

**Comment by SwePalm** [comment]
Got the same Error, even after restart :-(  

Using conda to install (got tsnecuda verion 1.0.dev384), CUDA 10.1, Nvidia driver 435.21,  Ubuntu 18.04

**Comment by DavidMChan** [comment]
@SwePalm - Which GPU are you using? Also, when running `nvidia-smi` what is the output? 
Also, FYI there's a bug with the version string right now, which we're fixing in the next release, but that is the latest version of our code.

**Comment by SwePalm** [comment]
Nvidia 1080 Ti, output from nvidia-smi does not reveal any info for me, but i can share it tomorrow with you. I run Tensorflow-GPU and Opencv on the same rig without issues.

**Comment by DavidMChan** [comment]
It would be great to see the output from the nvidia-smi when you get the chance. I can't reproduce this on my machine with a similar setup (CUDA 10,1, 1080Ti, Nvidia Driver 435.21, Ubuntu 19.04) with a clean install, so it's going to be a bit tricky to debug.

**Comment by SwePalm** [comment]
![Screenshot from 2019-09-11 08-30-03](https://user-images.githubusercontent.com/33499287/64673521-af0f0900-d46e-11e9-9a2e-bd413ed0ec89.png)

**Comment by DavidMChan** [comment]
@SwePalm , Can you comment on how you installed your conda environment, namely, can you run `conda list --explicit > spec-list.txt` and upload that file to a gist?

**Comment by SwePalm** [comment]
I will, when i am back...will be away from the desk for 2 weeks now, feel free to ping me again by the end of that week if i have forgotten. Sorry for the delay...
