### ISSUE TITLE
Build fail with undefined reference to FaissException

### ISSUE THREAD

**Issue by Vrroom** [CannyLab/tsne-cuda#67]
I followed the instructions as mentioned in the installation wiki. I'm stuck at the following error: 
```[  9%] Built target faiss
[ 12%] Built target glog
[ 12%] Built target gtest
[ 41%] Built target tsnecuda
[ 41%] Built target python_source_files
[ 41%] Built target write_version_string_to_python
[ 41%] Linking CXX executable tsne
CMakeFiles/tsne.dir/third_party/faiss/gpu/tsne_generated_GpuIndex.cu.o: In function `faiss::gpu::GpuIndex::search(long, float const*, long, float*, long*) const':
/sumitc/tsne-cuda/third_party/faiss/gpu/GpuIndex.cu:114: undefined reference to `faiss::FaissException::FaissException(std::string const&, char const*, char const*, int)'
CMakeFiles/tsne.dir/third_party/faiss/gpu/tsne_generated_GpuIndex.cu.o: In function `faiss::gpu::GpuIndex::GpuIndex(faiss::gpu::GpuResources*, int, faiss::MetricType, faiss::gpu::GpuIndexConfig)':
/sumitc/tsne-cuda/third_party/faiss/gpu/GpuIndex.cu:44: undefined reference to `faiss::FaissException::FaissException(std::string const&, char const*, char const*, int)'
/sumitc/tsne-cuda/third_party/faiss/gpu/GpuIndex.cu:38: undefined reference to `faiss::FaissException::FaissException(std::string const&, char const*, char const*, int)'
/sumitc/tsne-cuda/third_party/faiss/gpu/GpuIndex.cu:41: undefined reference to `faiss::FaissException::FaissException(std::string const&, char const*, char const*, int)'
CMakeFiles/tsne.dir/third_party/faiss/gpu/tsne_generated_GpuIndex.cu.o: In function `faiss::gpu::GpuIndex::addInternal_(long, float const*, long const*)':
/net/voxel07/misc/me/sumitc/tsne-cuda/third_party/faiss/gpu/GpuIndex.cu:77: undefined reference to `faiss::FaissException::FaissException(std::string const&, char const*, char const*, int)'
CMakeFiles/tsne.dir/third_party/faiss/gpu/tsne_generated_GpuIndexFlat.cu.o:/sumitc/tsne-cuda/third_party/faiss/gpu/GpuIndexFlat.cu:185: more undefined references to `faiss::FaissException::FaissException(std::string const&, char const*, char const*, int)' follow
collect2: error: ld returned 1 exit status
CMakeFiles/tsne.dir/build.make:83939: recipe for target 'tsne' failed
make[2]: *** [tsne] Error 1
CMakeFiles/Makefile2:182: recipe for target 'CMakeFiles/tsne.dir/all' failed
make[1]: *** [CMakeFiles/tsne.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2
```

Will appreciate any help :)

**Comment by DavidMChan** [comment]
It looks like there are some issues with your FAISS submodule version, can you give the compiler/CMAKE version, CUDA version, your OS, and the steps to reproduce (primarily, did you run git submodule init/git submodule update?). Also, can you export the full output of the CMAKE compile command to a GIST? (So I can check the path variables in the FIND_CMAKE sections?) 

It looks like FAISS isn't getting linked into the library right for you, or not getting correctly compiled.

**Comment by Vrroom** [comment]
Sorry for not providing this info earlier :)
cmake version 3.12.2
cuda version 9.1
OS Ubuntu 18.04

Here is the GIST:

https://gist.github.com/Vrroom/b5f899fa0966bff7875d20722203e8ee

Thanks a TON for looking into this!

**Comment by DavidMChan** [comment]
Sorry, can you rerun the cmake command as well? aka, `cmake .. CMAKE_ARGS`. One other thing to try (if you can) is removing the build directory, and trying again from scratch, aka:
```
rm -rf /path/to/build
mkdir /path/to/build
cd /path/to/build
cmake /tsnecuda rootdir/ CMAKE_ARGS
make
```
I'm not entirely sure what's happening since I can't reproduce the problem in a VM with your system setup.

**Comment by Vrroom** [comment]
I changed the CMakeLists.txt in the following way: 
```diff --git a/CMakeLists.txt b/CMakeLists.txt
index a16e330..22da3dc 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -53,7 +53,7 @@ SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")
 #-------------------------------------------------------------------------------
 SET(CUDA_SEPARABLE_COMPILATION ON)
 find_package(CUDA REQUIRED)
-SET(CUDA_HOST_COMPILER ${CXX})
+SET(CUDA_HOST_COMPILER "/usr/bin/gcc-4.9")
 SET(CUDA_PROPAGATE_HOST_FLAGS OFF)
 set(CUDA_NVCC_FLAGS ${CUDA_NVCC_FLAGS};
                     -O3
```
Because otherwise the build was failing (saying that GCC > 6 not supported).

Here is the cmake output: 
https://gist.github.com/Vrroom/b2aa6b0813348b12eff3e9ff45dbad37

**Comment by Vrroom** [comment]
I got past that error. I think I wasn't using one compiler version consistently. (Now I set CMAKE_C_COMPILER to gcc-4.9 and CMAKE_CXX_COMPILER to g++-4.9). 
But now I am getting the following error with glog: 
https://gist.github.com/Vrroom/631afc07943da2fddb34bc28109fdb47

I followed the suggestions at https://github.com/google/glog/issues/288 (I compiled latest gflags from source AND modified the CMakeLists.txt at third_party/glog to set gflags_DIR to the local install). Still unsuccessful!

Thanks :)

**Comment by Vrroom** [comment]
Figured out the error.
It turns out that the GCC version for libgflags was different than the one used in the current build. 
That is why the above mentioned error was occuring. 
Found this at the following link. https://github.com/gflags/gflags/issues/203

Thanks a lot David for taking your time out and helping me. Looking forward to using this tool
