### ISSUE TITLE
tsnecuda.test() fails

### ISSUE THREAD

**Issue by 22shivangi** [CannyLab/tsne-cuda#68]
I could install everything successfully, but I get errorwhen I run tsnecuda.test()

```
Initializing cuda handles... done.
KNN Computation... Faiss assertion 'err == cudaSuccess' failed in faiss::gpu::StackDeviceMemory::Stack::Stack(int, size_t) at /home/shivangi/Desktop/Projects/master_thesis/tsne-cuda/third_party/faiss/gpu/utils/StackDeviceMemory.cpp:33
Aborted (core dumped)
```

**Comment by 22shivangi** [comment]
It was GPU memory issue, cleaned up some memory. It works now

**Comment by yuheyuan** [comment]
> It was GPU memory issue, cleaned up some memory. It works now

how do you clean up some memory. Reset computer? I want to ask. Thank you

**Comment by shivangi-aneja** [comment]
> > It was GPU memory issue, cleaned up some memory. It works now
> 
> how do you clean up some memory. Reset computer? I want to ask. Thank you

I don't remember now; it's been quite some time. But hard reset should definitely help. if it doesn't, then I guess your machine doesn't have enough memory.
