### ISSUE TITLE
tsne-cuda returns matrix of NaNs on my 2d array

### ISSUE THREAD

**Issue by ghost1917** [CannyLab/tsne-cuda#70]
I installed and run tsne-cuda on my 2d array and it 
returned matrix of NaNs.
The original dataset doesn't contain NaNs and the library doesn't raise any errors,
just a matrix of empty values.
The method works fine on smaller size input data.
Colab notebook that reproduces bug:
https://colab.research.google.com/drive/15RL9VgqRTnd3DcoFKa9Cicv7_j8ZoRgD#scrollTo=scLTegl83MMe

OS: Ubuntu 18.04
CUDA: 10.0.130
NVIDIA-SMI:
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 430.50       Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   30C    P8    28W / 149W |      0MiB / 11441MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Comment by DavidMChan** [comment]
We'll take a look at it. Running with a higher perplexity seems fine - so it looks like there's a possible over/underflow because of the perplexity scaling. Since you only have 810 samples, I recommend running with BH-TSNE or Multicore-TSNE which use double precision.

**Comment by ghost1917** [comment]
Actually I found this issue on full dataset with shape (100000,512). But it also reproduces on its subsample with shape (810,3) as well. I just tried to provide a minimal reproducible case.

**Comment by ghost1917** [comment]
Oh, I found the reason of this issue. The dataset contains duplicated vectors. After the duplication cleaning your library works correctly

**Comment by monchin** [comment]
I also met the same problem, and I added each element a random little value, it worked. Thank you.
If we add a very little epsilon value to each vector-pair's distance in the source code, can this issue be avoided?

**Comment by DavidMChan** [comment]
@monchin , the reason that we don't add a small value in the source code is that a "small" value can be different for every application. We could expose a variable, but it seems to us more likely to cause bugs than to help fix them.

**Comment by rmrao** [comment]
I can see both sides of this argument. If we leave it as is, it might be good to have some sort of explicit warning if we detect NaNs.
