### ISSUE TITLE
tsnecuda is slower than sklearn tsne

### ISSUE THREAD

**Issue by mhusseinsh** [CannyLab/tsne-cuda#73]
I did a simple test to compare the runtime between tsnecuda and normal tsne from sklearn
and surprisingly, tsnecuda was much slower.
```
import numpy as np
from sklearn.manifold import TSNE
from tsnecuda import TSNE as TSNE_CUDA
# to measure exec time
from timeit import default_timer as timer
import random
RS = 20150101
  
# normal function to run on cpu 
def func(a):
    X = np.vstack([a])
    tsneData = TSNE(n_components=2, random_state=RS, perplexity=30).fit_transform(a)
  
# function optimized to run on gpu                           
def func2(a): 
    X = np.vstack([a])
    tsneData = TSNE_CUDA(n_components=2, random_seed=RS, perplexity=30).fit_transform(np.array(a))

if __name__=="__main__": 

    data = []
    for i in range (11):
        data1 = np.random.randint(low=0, high=255, size=100, dtype=np.uint8)
        data.append(data1)

    start = timer() 
    func(data) 
    print("without GPU:", timer()-start)     
    
    start = timer() 
    func2(data) 
    print("with GPU:", timer()-start) 
```
```
('without GPU:', 0.06844186782836914)
WARNING clustering 11 points to 3 centroids: please provide at least 117 training points
('with GPU:', 1.4468739032745361)
```

**Comment by DavidMChan** [comment]
This is the case for very small numbers of points (eg. the 11 you used in your example) - initializing memory on the GPU takes time, and using this library is designed for large numbers of points (so the initialization cost can be amortized across the computation cost). If your GPU is old, or very new, you can also have speed issues, since the kernel sizes are tuned for a very small number of GPUs.

**Comment by mhusseinsh** [comment]
Hello @DavidMChan 
is there a way that I can allocate/initialize the GPU once in the beginning of my script, so I don't need to load it or initialize it again when I call the function again?

**Comment by mhusseinsh** [comment]
@DavidMChan , and if this is yes.
If I have multiple GPUs on my machine, how can I specify which GPU to use?
From this
https://github.com/anderskm/gputil
I can get the free GPU of of my available ones, then I need to specify to tsnecuda to use this gpu, how can I do this?

**Comment by DavidMChan** [comment]
There is no way to pre-initialize the code. If you have very small numbers of points, then it is almost always better to use a CPU-based method. Our GPU-based method takes approximately the same amount of time to do 100 points, as it does to do 10,000 (making it much better for larger applications). 

You can specify the device using: `TSNE(device=X)`
