### ISSUE TITLE
OSError: libcublas.so.9.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Yocodeyo** [CannyLab/tsne-cuda#74]
I managed to install and import tsnecuda but this error came up when I tried:
tsne = TSNE(n_components=2, verbose=1, perplexity=100, learning_rate=250, n_iter=500)

OSError: libcublas.so.9.0: cannot open shared object file: No such file or directory

I have cuda 9.0 installed

**Comment by DavidMChan** [comment]
Please make sure that cublas is on your library path (and installed) - in some cases, it can be installed in a different directory from the /usr/local/cuda, which can cause issues.
