### ISSUE TITLE
tsne-cuda returns "No Visualization Terminal, continuing..." and can not plot

### ISSUE THREAD

**Issue by hohoking** [CannyLab/tsne-cuda#76]
Hello, 
I have tried before on the tsne-cuda package, it works very nicely! However, after a SSD failure and reinstall, I could not bring the script running again. I am wondering if there is any mistake when I installed the system and the drivers. 

Here is my system summary: 
Ubuntu 18.04.4 LTS
NVIDIA Card: _QUADRO P1000_
NVIDIA Driver Version:  _435.21_  CUDA Version: _10.1_

When run: nvcc --version
Cuda compilation tools, release 10.0, V10.0.130

When run the same script as before and try to plot using plotly.express package, this following error appreas and never show the figure. 

The error is : **No Visualization Terminal, continuing...**

Has someone faced similar problem before? Could you please give any hint? 

Finally, could any one recommend which version of Ubuntu and Nvidia driver and Cuda driver are working? Especially, for those who managed to run "use_interactive", would be very interesting.

Thank you very much!

**Comment by DavidMChan** [comment]
There should be no issue with the code - we were able to re-enable an underlying use-interactive feature, which allows you to visualize the run interactively using the visualize.py script in the visualization/ folder. (The error will induce a 10s wait to connect to the realtime visualization), and then continue with the code. Are you using the interactive visualization option? And if so, how are you doing this?
