### ISSUE TITLE
Is there any code for ImageNet dataset as the paper mentioned

### ISSUE THREAD

**Issue by hannahlee66** [CannyLab/tsne-cuda#77]
In the paper, it mentioned the method is able to visualize ImageNet very fast. However, I cannot find the code. Is there any code for this?

**Comment by DavidMChan** [comment]
We don't provide code for ImageNet, however you can easily run the ImageNet experiments by downloading pre-trained ImageNet codes, and using tsne-cuda on them (We don't use the python bindings, we use the C++ utility with the codes stored as an MNIST-style dataset).
