### ISSUE TITLE
Is there a way to only transform new data without fitting? 

### ISSUE THREAD

**Issue by pbashivan** [CannyLab/tsne-cuda#78]
Is there a way to only transform new data without fitting? Using the already computed projection. E.g. 

```
tsne = TSNE(n_components=2, perplexity=20, learning_rate=10)
tr_emb = tsne.fit_transform(train_data)
te_emb = tsne.transform(test_data)
```

**Comment by DavidMChan** [comment]
No. TSNE is a non-parametric embedding that works by matching distributions between your testing and your training data. There are modified TSNE algorithms with allow for this kind of incremental embedding, but primarily they work by taking the new point, embedding it randomly, and continuing the optimization. The only "correct" thing to do is to re-train your whole TSNE embedding whenever you have new data.
