### ISSUE TITLE
Whether this work supporting table data?

### ISSUE THREAD

**Issue by geometrylearner** [CannyLab/tsne-cuda#80]
I have test a sample by setting `n_components=3` which followed error:

`NotImplementedError: The current fit-tsne implementation does not support projection into dimensions other than 2 for now.`

I wonder whether this algorithm improving the training on table data, if so?

**Comment by DavidMChan** [comment]
The algorithm only supports projection into two dimensions, however will take as input an arbitrary number of dimensions. For 3D projections, see #71

**Comment by geometrylearner** [comment]
Of course it supports, search in kaggle.com, the ‘rapids umap’, there is an benchmark for higher dimension.




    



    
    
    



    
        
            
                
                    
                        
                    
                    
                        
                            geotoppos
                            
                            
                                
                                    邮箱：geotoppos@aliyun.com
                                
                        
                    
                
            
        
    


Signature is customized by Netease Mail Master


On 07/30/2020 12:08, David Chan wrote: 
The algorithm only supports projection into two dimensions, however will take as input an arbitrary number of dimensions. For 3D projections, see #71

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/CannyLab/tsne-cuda/issues/80#issuecomment-666089271",
"url": "https://github.com/CannyLab/tsne-cuda/issues/80#issuecomment-666089271",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
