### ISSUE TITLE
tsnecuda with CUDA10.2

### ISSUE THREAD

**Issue by vnesh-san** [CannyLab/tsne-cuda#81]
Could you guys please create a version for CUDA10.2. I have CUDA10.2 and I couldn't find any compatible versions.

Thanks

**Comment by RocStone** [comment]
Same problem

**Comment by rnrpereira** [comment]
Any news on that?
I am also trying to install but having problems.

My system:
Ubuntu 18.04
CUDA 10.2
Anaconda

`(tsne_cuda) rodrigo@rodrigo-System-Product-Name:~$ conda install tsnecuda cuda101 -c cannylab
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \ 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                 
                                                                                                                                       
UnsatisfiableError: The following specifications were found to be incompatible with each other:                                        



Package blas conflicts for:
mkl_random -> numpy[version='>=1.14,<2.0a0'] -> blas[version='*|1.0',build=openblas]
tsnecuda -> openblas -> blas[version='*|1.0',build=openblas]
mkl-service -> numpy[version='>=1.11.3,<2.0a0'] -> blas[version='*|*|1.0',build='mkl|openblas|openblas']
pytest-arraydiff -> numpy -> blas[version='*|*|1.0',build='mkl|openblas|mkl|openblas']
seaborn -> numpy -> blas[version='*|*|1.0',build='mkl|openblas|mkl|openblas']
mkl_fft -> numpy-base[version='>=1.0.6,<2.0a0'] -> blas[version='*|1.0',build=openblas]
astropy -> numpy[version='>=1.11.3,<2.0a0'] -> blas[version='*|*|1.0',build='mkl|openblas|mkl|openblas']
scikit-learn -> blas[version='*|*|1.0',build='mkl|openblas|mkl|openblas']
patsy -> numpy[version='>=1.4.0'] -> blas[version='*|*|1.0',build='mkl|openblas|mkl|openblas']
pandas -> numpy[version='>=1.14.6,<2.0a0'] -> blas[version='*|*|1.0',build='mkl|openblas|mkl|openblas']
numpy-base -> blas[version='*|*|1.0',build='mkl|openblas|mkl|openblas']
numba -> numpy[version='>=1.11,<1.12.0a0'] -> blas[version='*|*|1.0',build='mkl|openblas|mkl|openblas']
nltk -> numpy -> blas[version='*|*|1.0',build='mkl|openblas|mkl|openblas']
mkl_random -> blas[version='*|1.0',build=mkl]
bokeh -> numpy[version='>=1.7.1'] -> blas[version='*|*|1.0',build='mkl|openblas|mkl|openblas']
bottleneck -> numpy[version='>=1.11.3,<2.0a0'] -> blas[version='*|*|1.0',build='mkl|openblas|mkl|openblas']
statsmodels -> numpy[version='>=1.11.3,<2.0a0'] -> blas[version='*|*|1.0',build='mkl|openblas|mkl|openblas']
matplotlib-base -> numpy[version='>=1.14.6,<2.0a0'] -> blas[version='*|1.0',build='mkl|openblas|openblas']
pytables -> numexpr -> blas[version='*|*|1.0',build='mkl|openblas|mkl|openblas']
anaconda -> blas==1.0=mkl
_anaconda_depends -> blas
dask -> numpy[version='>=1.13.0'] -> blas[version='*|*|1.0',build='mkl|openblas|mkl|openblas']
scikit-image -> numpy[version='>=1.9.3,<2.0a0'] -> blas[version='*|*|1.0',build='mkl|openblas|mkl|openblas']
scipy -> blas[version='*|*|1.0',build='mkl|openblas|mkl|openblas']
anaconda -> numpy==1.14.0=py35h3dfced4_1 -> blas[version='*|*|1.0',build='mkl|openblas|openblas']
numexpr -> blas[version='*|*|1.0',build='mkl|openblas|mkl|openblas']
h5py -> numpy -> blas[version='*|*|1.0',build='mkl|openblas|mkl|openblas']
imageio -> numpy -> blas[version='*|*|1.0',build='mkl|openblas|mkl|openblas']
bkcharts -> numpy[version='>=1.7.1'] -> blas[version='*|*|1.0',build='mkl|openblas|mkl|openblas']
mkl-service -> blas==1.0=mkl
blas
mkl_fft -> blas[version='*|1.0',build=mkl]
matplotlib -> numpy -> blas[version='*|*|1.0',build='mkl|openblas|mkl|openblas']
pytest-astropy -> pytest-arraydiff[version='>=0.1'] -> numpy -> blas[version='*|*|1.0',build='mkl|openblas|mkl|openblas']
_anaconda_depends -> numexpr -> blas[version='*|*|1.0',build='mkl|openblas|mkl|openblas']
pywavelets -> numpy[version='>=1.11.3,<2.0a0'] -> blas[version='*|*|1.0',build='mkl|openblas|mkl|openblas']
pytest-doctestplus -> numpy[version='>=1.10'] -> blas[version='*|*|1.0',build='mkl|openblas|mkl|openblas']
numpy -> blas[version='*|*|1.0',build='mkl|openblas|mkl|openblas']
Package libopenblas conflicts for:
matplotlib-base -> numpy[version='>=1.14.6,<2.0a0'] -> numpy-base==1.15.4=py37h2f8d375_0 -> libopenblas[version='>=0.2.20,<0.2.21.0a0']
tsnecuda -> libopenblas
scikit-learn -> numpy[version='>=1.11.3,<2.0a0'] -> libopenblas[version='>=0.3.2,<0.3.3.0a0']
`

`# packages in environment at /home/rodrigo/anaconda3/envs/tsne_cuda:
#
# Name                    Version                   Build  Channel
_anaconda_depends         2020.02                  py37_0  
_libgcc_mutex             0.1                        main  
alabaster                 0.7.12                   py37_0  
anaconda                  custom                   py37_1  
anaconda-client           1.7.2                    py37_0  
anaconda-project          0.8.4                      py_0  
argh                      0.26.2                   py37_0  
asn1crypto                1.3.0                    py37_1  
astroid                   2.3.3                    py37_0  
astropy                   4.0.1.post1      py37h7b6447c_1  
atomicwrites              1.4.0                      py_0  
attrs                     19.3.0                     py_0  
autopep8                  1.5.3                      py_0  
babel                     2.8.0                      py_0  
backcall                  0.2.0                      py_0  
backports                 1.0                        py_2  
backports.shutil_get_terminal_size 1.0.0                    py37_2  
beautifulsoup4            4.9.1                    py37_0  
bitarray                  1.4.0            py37h7b6447c_0  
bkcharts                  0.2                      py37_0  
blas                      1.0                         mkl  
bleach                    3.1.5                      py_0  
blosc                     1.19.0               hd408876_0  
bokeh                     2.1.1                    py37_0  
boto                      2.49.0                   py37_0  
bottleneck                1.3.2            py37heb32a55_1  
brotlipy                  0.7.0           py37h7b6447c_1000  
bzip2                     1.0.8                h7b6447c_0  
ca-certificates           2020.6.24                     0  
cairo                     1.14.12              h8948797_3  
certifi                   2020.6.20                py37_0  
cffi                      1.14.0           py37h2e261b9_0  
chardet                   3.0.4                 py37_1003  
click                     7.1.2                      py_0  
cloudpickle               1.5.0                      py_0  
clyent                    1.2.2                    py37_1  
colorama                  0.4.3                      py_0  
contextlib2               0.6.0.post1                py_0  
cryptography              2.9.2            py37h1ba5d50_0  
curl                      7.71.1               hbc83047_1  
cycler                    0.10.0                   py37_0  
cython                    0.29.21          py37he6710b0_0  
cytoolz                   0.10.1           py37h7b6447c_0  
dask                      2.20.0                     py_0  
dask-core                 2.20.0                     py_0  
dbus                      1.13.16              hb2f20db_0  
decorator                 4.4.2                      py_0  
defusedxml                0.6.0                      py_0  
diff-match-patch          20200713                   py_0  
distributed               2.20.0                   py37_0  
docutils                  0.16                     py37_1  
entrypoints               0.3                      py37_0  
et_xmlfile                1.0.1                   py_1001  
expat                     2.2.9                he6710b0_2  
fastcache                 1.1.0            py37h7b6447c_0  
filelock                  3.0.12                     py_0  
flake8                    3.8.3                      py_0  
flask                     1.1.2                      py_0  
fontconfig                2.13.0               h9420a91_0  
freetype                  2.10.2               h5ab3b9f_0  
fribidi                   1.0.9                h7b6447c_0  
fsspec                    0.7.4                      py_0  
future                    0.18.2                   py37_1  
get_terminal_size         1.0.0                haa9412d_0  
gevent                    20.6.2           py37h7b6447c_0  
glib                      2.63.1               h5a9c865_0  
glob2                     0.7                        py_0  
gmp                       6.1.2                h6c8ec71_1  
gmpy2                     2.0.8            py37h10f8cd9_2  
graphite2                 1.3.14               h23475e2_0  
greenlet                  0.4.16           py37h7b6447c_0  
gst-plugins-base          1.14.0               hbbd80ab_1  
gstreamer                 1.14.0               hb453b48_1  
h5py                      2.10.0           py37h7918eee_0  
harfbuzz                  1.8.8                hffaf4a1_0  
hdf5                      1.10.4               hb1b8bf9_0  
heapdict                  1.0.1                      py_0  
html5lib                  1.1                        py_0  
hypothesis                5.18.3                     py_0  
icu                       58.2                 he6710b0_3  
idna                      2.10                       py_0  
imageio                   2.9.0                      py_0  
imagesize                 1.2.0                      py_0  
importlib-metadata        1.7.0                    py37_0  
importlib_metadata        1.7.0                         0  
intel-openmp              2020.1                      217  
intervaltree              3.0.2                      py_1  
ipykernel                 5.3.2            py37h5ca1d4c_0  
ipython                   7.16.1           py37h5ca1d4c_0  
ipython_genutils          0.2.0                    py37_0  
ipywidgets                7.5.1                      py_0  
isort                     4.3.21                   py37_0  
itsdangerous              1.1.0                    py37_0  
jbig                      2.1                  hdba287a_0  
jdcal                     1.4.1                      py_0  
jedi                      0.17.1                   py37_0  
jeepney                   0.4.3                      py_0  
jinja2                    2.11.2                     py_0  
joblib                    0.16.0                     py_0  
jpeg                      9b                   h024ee3a_2  
json5                     0.9.5                      py_0  
jsonschema                3.2.0                    py37_1  
jupyter                   1.0.0                    py37_7  
jupyter_client            6.1.6                      py_0  
jupyter_console           6.1.0                      py_0  
jupyter_core              4.6.3                    py37_0  
jupyterlab                2.1.5                      py_0  
jupyterlab_server         1.2.0                      py_0  
keyring                   21.2.1                   py37_0  
kiwisolver                1.2.0            py37hfd86e86_0  
krb5                      1.18.2               h173b8e3_0  
lazy-object-proxy         1.5.0            py37h7b6447c_0  
lcms2                     2.11                 h396b838_0  
ld_impl_linux-64          2.33.1               h53a641e_7  
libarchive                3.4.2                h62408e4_0  
libcurl                   7.71.1               h20c2e04_1  
libedit                   3.1.20191231         h14c3975_1  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0  
liblief                   0.10.1               he6710b0_0  
libllvm9                  9.0.1                h4a3c616_1  
libpng                    1.6.37               hbc83047_0  
libsodium                 1.0.18               h7b6447c_0  
libspatialindex           1.9.3                he6710b0_0  
libssh2                   1.9.0                h1ba5d50_1  
libstdcxx-ng              9.1.0                hdf63c60_0  
libtiff                   4.1.0                h2733197_1  
libtool                   2.4.6                h7b6447c_5  
libuuid                   1.0.3                h1bed415_2  
libxcb                    1.14                 h7b6447c_0  
libxml2                   2.9.10               he19cac6_1  
libxslt                   1.1.34               hc22bd24_0  
llvmlite                  0.33.0           py37hc6ec683_1  
locket                    0.2.0                    py37_1  
lxml                      4.5.2            py37hefd8a0e_0  
lz4-c                     1.9.2                he6710b0_0  
lzo                       2.10                 h7b6447c_2  
markupsafe                1.1.1            py37h14c3975_1  
matplotlib                3.2.2                         0  
matplotlib-base           3.2.2            py37hef1b27d_0  
mccabe                    0.6.1                    py37_1  
mistune                   0.8.4           py37h14c3975_1001  
mkl                       2020.1                      217  
mkl-service               2.3.0            py37he904b0f_0  
mkl_fft                   1.1.0            py37h23d657b_0  
mkl_random                1.1.1            py37h0573a6f_0  
mock                      4.0.2                      py_0  
more-itertools            8.4.0                      py_0  
mpc                       1.1.0                h10f8cd9_1  
mpfr                      4.0.2                hb69a4c5_1  
mpmath                    1.1.0                    py37_0  
msgpack-python            1.0.0            py37hfd86e86_1  
multipledispatch          0.6.0                    py37_0  
nbconvert                 5.6.1                    py37_1  
nbformat                  5.0.7                      py_0  
ncurses                   6.2                  he6710b0_1  
networkx                  2.4                        py_1  
nltk                      3.5                        py_0  
nose                      1.3.7                 py37_1004  
notebook                  6.0.3                    py37_0  
numba                     0.50.1           py37h0573a6f_1  
numexpr                   2.7.1            py37h423224d_0  
numpy                     1.18.5           py37ha1c710e_0  
numpy-base                1.18.5           py37hde5b4d6_0  
numpydoc                  1.1.0                      py_0  
olefile                   0.46                     py37_0  
openpyxl                  3.0.4                      py_0  
openssl                   1.1.1g               h7b6447c_0  
packaging                 20.4                       py_0  
pandas                    1.0.5            py37h0573a6f_0  
pandoc                    2.10                          0  
pandocfilters             1.4.2                    py37_1  
pango                     1.42.4               h049681c_0  
parso                     0.7.0                      py_0  
partd                     1.1.0                      py_0  
patchelf                  0.11                 he6710b0_0  
path                      13.1.0                   py37_0  
path.py                   12.4.0                        0  
pathlib2                  2.3.5                    py37_1  
pathtools                 0.1.2                      py_1  
patsy                     0.5.1                    py37_0  
pcre                      8.44                 he6710b0_0  
pep8                      1.7.1                    py37_0  
pexpect                   4.8.0                    py37_1  
pickleshare               0.7.5                 py37_1001  
pillow                    7.2.0            py37hb39fc2d_0  
pip                       20.1.1                   py37_1  
pixman                    0.40.0               h7b6447c_0  
pkginfo                   1.5.0.1                  py37_0  
pluggy                    0.13.1                   py37_0  
ply                       3.11                     py37_0  
prometheus_client         0.8.0                      py_0  
prompt-toolkit            3.0.5                      py_0  
prompt_toolkit            3.0.5                         0  
psutil                    5.7.0            py37h7b6447c_0  
ptyprocess                0.6.0                    py37_0  
py                        1.9.0                      py_0  
py-lief                   0.10.1           py37h403a769_0  
pycodestyle               2.6.0                      py_0  
pycosat                   0.6.3            py37h7b6447c_0  
pycparser                 2.20                       py_2  
pycrypto                  2.6.1           py37h7b6447c_10  
pycurl                    7.43.0.5         py37h1ba5d50_0  
pydocstyle                5.0.2                      py_0  
pyflakes                  2.2.0                      py_0  
pygments                  2.6.1                      py_0  
pylint                    2.4.4                    py37_0  
pyodbc                    4.0.30           py37he6710b0_0  
pyopenssl                 19.1.0                     py_1  
pyparsing                 2.4.7                      py_0  
pyqt                      5.9.2            py37h05f1152_2  
pyrsistent                0.16.0           py37h7b6447c_0  
pysocks                   1.7.1                    py37_1  
pytables                  3.6.1            py37h71ec239_0  
pytest                    5.4.3                    py37_0  
pytest-arraydiff          0.3              py37h39e3cac_0  
pytest-astropy            0.8.0                      py_0  
pytest-astropy-header     0.1.2                      py_0  
pytest-doctestplus        0.7.0                      py_0  
pytest-openfiles          0.5.0                      py_0  
pytest-remotedata         0.3.2                    py37_0  
python                    3.7.7           hcf32534_0_cpython  
python-dateutil           2.8.1                      py_0  
python-jsonrpc-server     0.3.4                      py_1  
python-language-server    0.34.1                   py37_0  
python-libarchive-c       2.9                        py_0  
pytz                      2020.1                     py_0  
pywavelets                1.1.1            py37h7b6447c_0  
pyxdg                     0.26                       py_0  
pyyaml                    5.3.1            py37h7b6447c_1  
pyzmq                     19.0.1           py37he6710b0_1  
qdarkstyle                2.8.1                      py_0  
qt                        5.9.7                h5867ecd_1  
qtawesome                 0.7.2                      py_0  
qtconsole                 4.7.5                      py_0  
qtpy                      1.9.0                      py_0  
readline                  8.0                  h7b6447c_0  
regex                     2020.6.8         py37h7b6447c_0  
requests                  2.24.0                     py_0  
ripgrep                   11.0.2               he32d670_0  
rope                      0.17.0                     py_0  
rtree                     0.9.4                    py37_1  
ruamel_yaml               0.15.87          py37h7b6447c_1  
scikit-image              0.16.2           py37h0573a6f_0  
scikit-learn              0.23.1           py37h423224d_0  
scipy                     1.5.0            py37h0b6359f_0  
seaborn                   0.10.1                     py_0  
secretstorage             3.1.2                    py37_1  
send2trash                1.5.0                    py37_0  
setuptools                49.2.0                   py37_0  
simplegeneric             0.8.1                    py37_2  
singledispatch            3.4.0.3                  py37_0  
sip                       4.19.8           py37hf484d3e_0  
six                       1.15.0                     py_0  
snappy                    1.1.8                he6710b0_0  
snowballstemmer           2.0.0                      py_0  
sortedcollections         1.2.1                      py_0  
sortedcontainers          2.2.2                      py_0  
soupsieve                 2.0.1                      py_0  
sphinx                    3.1.2                      py_0  
sphinxcontrib             1.0                      py37_1  
sphinxcontrib-applehelp   1.0.2                      py_0  
sphinxcontrib-devhelp     1.0.2                      py_0  
sphinxcontrib-htmlhelp    1.0.3                      py_0  
sphinxcontrib-jsmath      1.0.1                      py_0  
sphinxcontrib-qthelp      1.0.3                      py_0  
sphinxcontrib-serializinghtml 1.1.4                      py_0  
sphinxcontrib-websupport  1.2.3                      py_0  
spyder                    4.1.4                    py37_0  
spyder-kernels            1.9.2                    py37_0  
sqlalchemy                1.3.18           py37h7b6447c_0  
sqlite                    3.32.3               h62c20be_0  
statsmodels               0.11.1           py37h7b6447c_0  
sympy                     1.6.1                    py37_0  
tbb                       2020.0               hfd86e86_0  
tblib                     1.6.0                      py_0  
terminado                 0.8.3                    py37_0  
testpath                  0.4.4                      py_0  
threadpoolctl             2.1.0              pyh5ca1d4c_0  
tk                        8.6.10               hbc83047_0  
toml                      0.10.1                     py_0  
toolz                     0.10.0                     py_0  
tornado                   6.0.4            py37h7b6447c_1  
tqdm                      4.47.0                     py_0  
traitlets                 4.3.3                    py37_0  
typing_extensions         3.7.4.2                    py_0  
ujson                     1.35             py37h14c3975_0  
unicodecsv                0.14.1                   py37_0  
unixodbc                  2.3.7                h14c3975_0  
urllib3                   1.25.9                     py_0  
watchdog                  0.10.3                   py37_0  
wcwidth                   0.2.5                      py_0  
webencodings              0.5.1                    py37_1  
werkzeug                  1.0.1                      py_0  
wheel                     0.34.2                   py37_0  
widgetsnbextension        3.5.1                    py37_0  
wrapt                     1.12.1           py37h7b6447c_1  
wurlitzer                 2.0.1                    py37_0  
xlrd                      1.2.0                    py37_0  
xlsxwriter                1.2.9                      py_0  
xlwt                      1.3.0                    py37_0  
xz                        5.2.5                h7b6447c_0  
yaml                      0.2.5                h7b6447c_0  
yapf                      0.30.0                     py_0  
zeromq                    4.3.2                he6710b0_2  
zict                      2.0.0                      py_0  
zipp                      3.1.0                      py_0  
zlib                      1.2.11               h7b6447c_3  
zope                      1.0                      py37_1  
zope.event                4.4                      py37_0  
zope.interface            4.7.1            py37h7b6447c_0  
zstd                      1.4.5                h0b5b093_0 `

**Comment by DavidMChan** [comment]
The reason that this is taking so long, is that in CUDA 10.2, cublas was split into libcublas.10.2.x and libcublasLt.10.2.x. This means that the latest version of CMake (3.18) is required to compile for CUDA 10.2, however 3.18 isn't available yet in the anaconda repositories. This means that we either A) have to wait for CMake 3.18, or B) have to figure out how to bypass the anaconda version of cmake, and use a system cmake to build the package. 

I'm working on option B, however I don't know if a solution exists, or how long it will take.

**Comment by DavidMChan** [comment]
@vnesh-san / @RocStone / @rnrpereira  - I've uploaded a beta version to my anaconda channel - can you try the following:
```
conda install -c davidmchan -c conda-forge cuda102 tsnecuda
```

**Comment by rnrpereira** [comment]
Thanks David!
The environment I'm using (tsne_cuda) has python 3.7.
However,
``conda install -c davidmchan -c conda-forge cuda102 tsnecuda` `
is not working!

Rodrigo

**Comment by DavidMChan** [comment]
Can you please post the full error message?

**Comment by rnrpereira** [comment]
```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: - 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
```
still going ....
....

**Comment by DavidMChan** [comment]
Are you installing in a clean conda environment? If not, which packages do you have installed? It would be great to know what's conflicting, so I can troubleshoot our build strictness. If you're installing in a clean environment, then that's even more worrying. The conda install should produce a list of conflicts after the above messages.

**Comment by rnrpereira** [comment]
I'm installimg in a python 3.7 env. With numpy, etc... I sent the full
content of the environment in my previous comment.

R.

Em sex, 24 de jul de 2020 17:56, David Chan <notifications@github.com>
escreveu:

**Comment by jj0mst** [comment]
Hello. I don't know about CUDA 10.2, but I have encountered the same problems mentioned here when I tried installing on different machines, all running CUDA 11.2.
@DavidMChan I also tried installing tsnecuda 3.0 from your channel but I still get unresolvable conflicts.
Do you have any plans to support newer versions of CUDA?

**Comment by DavidMChan** [comment]
Sorry we've been somewhat MIA for these comments. The problem with adding support beyond 10.2 comes in the form of a restructure to CUBLAS, which removed some of the library functions which we depend on. They've probably been replaced with something new, however as a PhD student, I haven't really had time to go back and explore the replacements. 

That being said, I believe the code on the development branch  (/dev) may compile from scratch with CUDA 11.x and for modern CUDA versions. In this code, we replaced the offending CUBLAS code with an updated function which is slightly slower (however compensated with improvements to the rest of the code space). Unfortunately, with this code, I haven't had the time to figure out anaconda's packaging system to get the branch to build correctly through the conda build/link system. 

Thus, I could use some help in two places:
- Confirming that the dev version works with 11.x
- Updating the anaconda package build process with said version

**Comment by DavidMChan** [comment]
This should be resolved in the latest code release!
