### ISSUE TITLE
Error installing tsnecuda on conda 4.8.3 for cuda 10.1

### ISSUE THREAD

**Issue by miquelmassot** [CannyLab/tsne-cuda#84]
Hi,

I am shipping a conda environment for python 3.7.7 with cuda 10.1 inside a docker container. When I run the instruction `conda install -c cannylab tsnecuda` the process fails with the following error.

```
LinkError: pre-link script failed for package cannylab::tsnecuda-2.1.0-cuda101
location of failed script: /opt/conda/pkgs/tsnecuda-2.1.0-cuda101/bin/.tsnecuda-pre-link.sh
==> script messages <==
<None>
==> script output <==
stdout:
stderr: + /opt/conda/envs/cuda_10_1/bin/python /opt/conda/pkgs/tsnecuda-2.1.0-cuda101/link.py
/opt/conda/pkgs/tsnecuda-2.1.0-cuda101/bin/.tsnecuda-pre-link.sh: line 2: /opt/conda/envs/cuda_10_1/bin/python: No such file or directory

return code: 127
```

**Comment by yefremenko** [comment]
Had the same problem on a newly created conda environment. 
Try installing python first:
```conda install python=3.6```
Worked for me.

**Comment by DavidMChan** [comment]
This should be fixed now with the most recent code release. Feel free to re-open if you're still having problems.
