### ISSUE TITLE
tsnecuda causes error when cloning conda environment

### ISSUE THREAD

**Issue by FreddieM007** [CannyLab/tsne-cuda#85]
I have **tsnecuda** installed in a local conda **env1** using:
`conda install tsnecuda cuda101 -c cannylab`

Cloning **env1** to **env2** using this command
`conda create -n env2 --clone env1`
causes the error attached in the file "[conda_tsnecuda_error.txt](https://github.com/CannyLab/tsne-cuda/files/5197788/conda_tsnecuda_error.txt)"
which prevents cloning the environment.

Please fix this issue since it causes a lot of trouble.
Thanks!!!

**Comment by DavidMChan** [comment]
This should be resolved as of the 3.0.0 release. Feel free to re-open if you're still having issues!
