### ISSUE TITLE
Build from source error! "naive_tsne.h" not find!

### ISSUE THREAD

**Issue by JincanDeng** [CannyLab/tsne-cuda#89]
I build the project from source according to the instruction.
But it fails, and this is the logs:

`tsne-cuda/src/test/test.cu:14:24: fatal error: naive_tsne.h: No such file or directory`

**Comment by DavidMChan** [comment]
Thanks for the report! Because the tests are outdated, we don't often build them :)

**Comment by DavidMChan** [comment]
This is resolved in the latest release!
