### ISSUE TITLE
Request: tsnecuda for conda

### ISSUE THREAD

**Issue by ktamiola** [CannyLab/tsne-cuda#9]
Since conda provides various versions of `faiss`:

```
# CPU version only
conda install faiss-cpu -c pytorch
# Make sure you have CUDA installed before installing faiss-gpu, otherwise it falls back to CPU version
conda install faiss-gpu -c pytorch # [DEFAULT]For CUDA8.0
conda install faiss-gpu cuda90 -c pytorch # For CUDA9.0
conda install faiss-gpu cuda91 -c pytorch # For CUDA9.1
# cuda90/cuda91 shown above is a feature, it doesn't install CUDA for you.
```

It would be great if you could make a conda-specific `tsnecuda` package.

**Comment by rmrao** [comment]
Conda support is now available! It doesn't use conda's `faiss` since this doesn't quite provide what we want. But it packages it's own version as a shared library so it should work fine for everyone. The version we uploaded requires CUDA 9.0, we haven't added multiple versions for different CUDA versions. You should be able to install with 

```bash
conda install tsnecuda -c cannylab
```

**Comment by ygjwd12345** [comment]
hi  i also face the problem when I use"conda install tsnecuda -c cannylab", it doesn't work

**Comment by cinastanbean** [comment]
hi, 我通过如下方式解决了。@ygjwd12345 

遇到的错误：OSError: libfaiss.so: cannot open shared object file: No such file or directory

解决方法：
1.  conda install tsnecuda -c cannylab
2. find / -name libfaiss.so # 记录下路径
2. find / -name libopenblas.so.0 # 记录下路径
3. 类似操作：export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/conda/pkgs/tsnecuda-0.2.1-py36h6fed035_0/lib/:/opt/conda/pkgs/openblas-0.2.19-0/lib #路径写第二步记录下的路径。

这样就可以解决。

-------------------------------

其他问题：Faiss assertion 'err == cudaSuccess' failed in faiss::gpu::StackDeviceMemory::Stack::Stack(int, size_t) at /home/david/Code/tsne-cuda/third_party/faiss/gpu/utils/StackDeviceMemory.cpp:33
Aborted

解决方法：cuda内存不够，腾出空间即可。
