### ISSUE TITLE
Possibly incorrect gradient norm calculation

### ISSUE THREAD

**Issue by zbjornson** [CannyLab/tsne-cuda#90]
Hello,

This code:

https://github.com/CannyLab/tsne-cuda/blob/568559b33900982cd18a90195efadea8331fb66a/src/fit_tsne.cu#L450-L458

looks like it equates to `Sum( Sqrt(x_i*x_i + y_i*y_i) for all i )`. Is that correct? I think the sqrt needs to move outside of the sum, if so.

**Comment by rmrao** [comment]
Yeah I think you’re right. Thanks for the catch!
