### ISSUE TITLE
Docker image for running TSNE-CUDA

### ISSUE THREAD

**Issue by LucaCappelletti94** [CannyLab/tsne-cuda#92]
Hello and thank you for making this library!

Since it may be difficult for some people (myself definitely included in the aforementioned group) to figure out how to install tsne-cuda from conda (every attempt always ends up in freezing) and compiling it from source always fails for some error which sends me into a never-ending rabbit hole of additional errors, I believe that a Docker image that wraps all the requirements to get a TSNE-CUDA VM up and running would be of great help.

How could I help to make one?

Thank you!

**Comment by DavidMChan** [comment]
This is resolved as of the latest release! See the docker images here: https://github.com/CannyLab/tsne-cuda/tree/master/packaging - which are designed for building TSNE-CUDA.
