### ISSUE TITLE
Errors from building from the source

### ISSUE THREAD

**Issue by Solacex** [CannyLab/tsne-cuda#93]
![image](https://user-images.githubusercontent.com/12868455/103321636-bc4e6d80-4a8e-11eb-9935-bfde4a90e85e.png)

During the make, it seems that libopenblas.so could not be found, but it already exists in the corresponding directory.
![image](https://user-images.githubusercontent.com/12868455/103321804-7ba32400-4a8f-11eb-9e9d-21189ff4c3c7.png)

**Comment by DavidMChan** [comment]
It looks like in this case, it's trying to find libgfortran.so.3, which your version of libopenblas.so is linked against. Can you confirm that the libgfortran.so.3 is on your linker path?

**Comment by Solacex** [comment]
I found that the machine has already installed with libgfortran.so.4 rather than 3, so should I reinstall to the older version of libgfortran?

**Comment by Solacex** [comment]
This bug has been fixed by copying libgfortran.so.3 from another machine, so I close this issue.
