### ISSUE TITLE
Squared Euclidean as default metric for NN search

### ISSUE THREAD

**Issue by divyegala** [CannyLab/tsne-cuda#97]
Is there a reason Squared Euclidean is used as a default for computing the KNN graph, and not just Euclidean?

**Comment by DavidMChan** [comment]
Using the squared distance is much more efficient. In addition, this is one of the few metrics supported upstream by FAISS. The next release of tsnecuda (hopefully coming soon) will support the other upstream metrics from FAISS:

    METRIC_INNER_PRODUCT, ///< maximum inner product search
    METRIC_L2,            ///< squared L2 search
    METRIC_L1,                ///< L1 (aka cityblock)
    METRIC_Linf,              ///< infinity distance
    METRIC_Lp,                ///< L_p distance
    METRIC_Canberra,
    METRIC_BrayCurtis,
    METRIC_JensenShannon,
